// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApolice.Shared.Infrastructure.Persistence;

#nullable disable

namespace WebApolice.Shared.Infrastructure.Persistence.Migrations.Core
{
    [DbContext(typeof(CoreDbContext))]
    partial class CoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.Banco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.HasKey("Id")
                        .HasName("banco_pkey");

                    b.HasIndex(new[] { "Codigo" }, "ix_banco_codigo")
                        .HasDatabaseName("ix_banco_codigo");

                    b.HasIndex(new[] { "LegadoId" }, "ux_banco_legado")
                        .IsUnique()
                        .HasDatabaseName("ix_banco_legado_id")
                        .HasFilter("(legado_id IS NOT NULL)");

                    b.ToTable("banco", "core");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.Cidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("EstadoId")
                        .HasColumnType("bigint")
                        .HasColumnName("estado_id");

                    b.Property<int?>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeNormalizado")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_normalizado");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("uf")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("cidade_pkey");

                    b.HasIndex("EstadoId")
                        .HasDatabaseName("ix_cidade_estado_id");

                    b.HasIndex(new[] { "Nome" }, "ix_cidade_nome_trgm")
                        .HasDatabaseName("ix_cidade_nome");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Nome" }, "ix_cidade_nome_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Nome" }, "ix_cidade_nome_trgm"), new[] { "gin_trgm_ops" });

                    b.HasIndex(new[] { "LegadoId" }, "ux_cidade_legado")
                        .IsUnique()
                        .HasDatabaseName("ix_cidade_legado_id")
                        .HasFilter("(legado_id IS NOT NULL)");

                    b.ToTable("cidade", "core");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.Estado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("uf")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("estado_pkey");

                    b.HasIndex(new[] { "Uf" }, "estado_uf_key")
                        .IsUnique()
                        .HasDatabaseName("ix_estado_uf");

                    b.ToTable("estado", "core");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.Pessoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DocumentoPrincipal")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("documento_principal");

                    b.Property<string>("DocumentoPrincipalLimpo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento_principal_limpo");

                    b.Property<bool>("DocumentoValido")
                        .HasColumnType("boolean")
                        .HasColumnName("documento_valido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeNormalizado")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_normalizado");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short?>("Sexo")
                        .HasColumnType("smallint")
                        .HasColumnName("sexo");

                    b.Property<short>("TipoPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("tipo_pessoa");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pessoa_pkey");

                    b.HasIndex(new[] { "DocumentoPrincipalLimpo" }, "ix_pessoa_documento_limpo")
                        .HasDatabaseName("ix_pessoa_documento_principal_limpo");

                    b.HasIndex(new[] { "DocumentoValido" }, "ix_pessoa_documento_valido")
                        .HasDatabaseName("ix_pessoa_documento_valido");

                    b.HasIndex(new[] { "Nome" }, "ix_pessoa_nome_trgm")
                        .HasDatabaseName("ix_pessoa_nome");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Nome" }, "ix_pessoa_nome_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Nome" }, "ix_pessoa_nome_trgm"), new[] { "gin_trgm_ops" });

                    b.ToTable("pessoa", "core");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.PessoaContato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean")
                        .HasColumnName("principal");

                    b.Property<string>("TipoContato")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_contato");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("valor");

                    b.Property<string>("ValorNormalizado")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("valor_normalizado");

                    b.HasKey("Id")
                        .HasName("pessoa_contato_pkey");

                    b.HasIndex(new[] { "PessoaId" }, "ix_pessoa_contato_pessoa")
                        .HasDatabaseName("ix_pessoa_contato_pessoa_id");

                    b.HasIndex(new[] { "TipoContato" }, "ix_pessoa_contato_tipo")
                        .HasDatabaseName("ix_pessoa_contato_tipo_contato");

                    b.ToTable("pessoa_contato", "core");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.PessoaContatoInstitucional", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("departamento");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<string>("Ramal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ramal");

                    b.Property<string>("Telefone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pessoa_contato_institucional_pkey");

                    b.HasIndex("PessoaId")
                        .HasDatabaseName("ix_pessoa_contato_institucional_pessoa_id");

                    b.ToTable("pessoa_contato_institucional", "core");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.PessoaDocumento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataEmissao")
                        .HasColumnType("date")
                        .HasColumnName("data_emissao");

                    b.Property<string>("Numero")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero");

                    b.Property<string>("NumeroLimpo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_limpo");

                    b.Property<string>("OrgaoEmissor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("orgao_emissor");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean")
                        .HasColumnName("principal");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_documento");

                    b.HasKey("Id")
                        .HasName("pessoa_documento_pkey");

                    b.HasIndex(new[] { "NumeroLimpo" }, "ix_pessoa_documento_numero")
                        .HasDatabaseName("ix_pessoa_documento_numero_limpo");

                    b.HasIndex(new[] { "PessoaId" }, "ix_pessoa_documento_pessoa")
                        .HasDatabaseName("ix_pessoa_documento_pessoa_id");

                    b.ToTable("pessoa_documento", "core");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.PessoaEndereco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cep");

                    b.Property<long?>("CidadeId")
                        .HasColumnType("bigint")
                        .HasColumnName("cidade_id");

                    b.Property<string>("Complemento")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("complemento");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("LegadoSituacaoEndereco")
                        .HasColumnType("integer")
                        .HasColumnName("legado_situacao_endereco");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Numero")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("numero");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean")
                        .HasColumnName("principal");

                    b.Property<string>("TipoEndereco")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_endereco")
                        .HasDefaultValueSql("'principal'::character varying");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("uf")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pessoa_endereco_pkey");

                    b.HasIndex("CidadeId")
                        .HasDatabaseName("ix_pessoa_endereco_cidade_id");

                    b.HasIndex(new[] { "PessoaId" }, "ix_pessoa_endereco_pessoa")
                        .HasDatabaseName("ix_pessoa_endereco_pessoa_id");

                    b.ToTable("pessoa_endereco", "core");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.Cidade", b =>
                {
                    b.HasOne("WebApolice.Shared.Infrastructure.Persistence.Models.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("cidade_estado_id_fkey");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.PessoaContato", b =>
                {
                    b.HasOne("WebApolice.Shared.Infrastructure.Persistence.Models.Pessoa", "Pessoa")
                        .WithMany("PessoaContatos")
                        .HasForeignKey("PessoaId")
                        .IsRequired()
                        .HasConstraintName("pessoa_contato_pessoa_id_fkey");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.PessoaContatoInstitucional", b =>
                {
                    b.HasOne("WebApolice.Shared.Infrastructure.Persistence.Models.Pessoa", "Pessoa")
                        .WithMany("PessoaContatoInstitucionals")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("pessoa_contato_institucional_pessoa_id_fkey");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.PessoaDocumento", b =>
                {
                    b.HasOne("WebApolice.Shared.Infrastructure.Persistence.Models.Pessoa", "Pessoa")
                        .WithMany("PessoaDocumentos")
                        .HasForeignKey("PessoaId")
                        .IsRequired()
                        .HasConstraintName("pessoa_documento_pessoa_id_fkey");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.PessoaEndereco", b =>
                {
                    b.HasOne("WebApolice.Shared.Infrastructure.Persistence.Models.Cidade", "Cidade")
                        .WithMany("PessoaEnderecos")
                        .HasForeignKey("CidadeId")
                        .HasConstraintName("pessoa_endereco_cidade_id_fkey");

                    b.HasOne("WebApolice.Shared.Infrastructure.Persistence.Models.Pessoa", "Pessoa")
                        .WithMany("PessoaEnderecos")
                        .HasForeignKey("PessoaId")
                        .IsRequired()
                        .HasConstraintName("pessoa_endereco_pessoa_id_fkey");

                    b.Navigation("Cidade");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.Cidade", b =>
                {
                    b.Navigation("PessoaEnderecos");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.Estado", b =>
                {
                    b.Navigation("Cidades");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.Pessoa", b =>
                {
                    b.Navigation("PessoaContatoInstitucionals");

                    b.Navigation("PessoaContatos");

                    b.Navigation("PessoaDocumentos");

                    b.Navigation("PessoaEnderecos");
                });
#pragma warning restore 612, 618
        }
    }
}
