/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--cor-marca-principal)',
        'primary-hover': 'var(--cor-marca-principal-hover)',
        'primary-ativa': 'var(--cor-marca-principal-ativa)',
        'primary-suave': 'var(--cor-marca-principal-suave)',
        'primary-borda': 'var(--cor-marca-principal-borda)',
        'primary-texto': 'var(--cor-marca-principal-texto)',
        'fundo-aplicacao': 'var(--cor-fundo-aplicacao)',
        'fundo-superficie': 'var(--cor-fundo-superficie)',
        'fundo-elevado': 'var(--cor-fundo-elevado)',
        'fundo-overlay': 'var(--cor-fundo-overlay)',
        'texto-principal': 'var(--cor-texto-principal)',
        'texto-secundario': 'var(--cor-texto-secundario)',
        'texto-inverso': 'var(--cor-texto-inverso)',
        borda: 'var(--cor-borda)',
        'borda-forte': 'var(--cor-borda-forte)',
        foco: 'var(--cor-foco)',
        desabilitado: 'var(--cor-desabilitado)',
        'desabilitado-fundo': 'var(--cor-desabilitado-fundo)',
        'desabilitado-texto': 'var(--cor-desabilitado-texto)',
        sucesso: 'var(--cor-sucesso)',
        'sucesso-fundo': 'var(--cor-sucesso-fundo)',
        'sucesso-borda': 'var(--cor-sucesso-borda)',
        erro: 'var(--cor-erro)',
        'erro-fundo': 'var(--cor-erro-fundo)',
        'erro-borda': 'var(--cor-erro-borda)',
        alerta: 'var(--cor-alerta)',
        'alerta-fundo': 'var(--cor-alerta-fundo)',
        'alerta-borda': 'var(--cor-alerta-borda)',
        informacao: 'var(--cor-informacao)',
        'informacao-fundo': 'var(--cor-informacao-fundo)',
        'informacao-borda': 'var(--cor-informacao-borda)',
      },
      spacing: {
        1: 'var(--espaco-1)',
        2: 'var(--espaco-2)',
        3: 'var(--espaco-3)',
        4: 'var(--espaco-4)',
        5: 'var(--espaco-5)',
        6: 'var(--espaco-6)',
        8: 'var(--espaco-8)',
        10: 'var(--espaco-10)',
      }
    },
  },
  plugins: [],
}
