// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApolice.Modulos.Convenio.src.WebApolice.Modulos.Convenio.Infrastructure.Persistence;

#nullable disable

namespace WebApolice.Modulos.Convenio.Infrastructure.Migrations
{
    [DbContext(typeof(ConvenioDbContext))]
    [Migration("20260813214221_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApolice.Modulos.Convenio.src.WebApolice.Modulos.Convenio.Infrastructure.Persistence.Models.CorsanCliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<long?>("ClienteVinculoId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_vinculo_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Empresa")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("empresa");

                    b.Property<bool?>("Funcionario")
                        .HasColumnType("boolean")
                        .HasColumnName("funcionario");

                    b.Property<string>("Grupo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("grupo");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<string>("Rubrica")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rubrica");

                    b.HasKey("Id")
                        .HasName("corsan_cliente_pkey");

                    b.HasIndex(new[] { "ClienteId" }, "ix_corsan_cliente_cliente");

                    b.ToTable("corsan_cliente", "convenio");
                });

            modelBuilder.Entity("WebApolice.Modulos.Convenio.src.WebApolice.Modulos.Convenio.Infrastructure.Persistence.Models.CorsanPropostum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<long?>("ClienteVinculoId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_vinculo_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Empresa")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("empresa");

                    b.Property<string>("Grupo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("grupo");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<long>("PropostaId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_id");

                    b.Property<string>("Rubrica")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rubrica");

                    b.HasKey("Id")
                        .HasName("corsan_proposta_pkey");

                    b.HasIndex(new[] { "ClienteId" }, "ix_corsan_proposta_cliente");

                    b.HasIndex(new[] { "PropostaId" }, "ux_corsan_proposta")
                        .IsUnique();

                    b.ToTable("corsan_proposta", "convenio");
                });

            modelBuilder.Entity("WebApolice.Modulos.Convenio.src.WebApolice.Modulos.Convenio.Infrastructure.Persistence.Models.SiapeCliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Agencia")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("agencia");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Categoria")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("categoria");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<long?>("ClienteVinculoId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_vinculo_id");

                    b.Property<string>("Contrato")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contrato");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DigitoVerificador")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("digito_verificador");

                    b.Property<string>("Funcao")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("funcao");

                    b.Property<string>("Instituidor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("instituidor");

                    b.Property<string>("Instituto")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("instituto");

                    b.Property<long?>("OrgaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("orgao_id");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<string>("Setor")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("setor");

                    b.Property<string>("Siape")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("siape");

                    b.HasKey("Id")
                        .HasName("siape_cliente_pkey");

                    b.HasIndex("OrgaoId");

                    b.HasIndex(new[] { "ClienteId" }, "ix_siape_cliente_cliente");

                    b.HasIndex(new[] { "Siape" }, "ix_siape_cliente_siape");

                    b.ToTable("siape_cliente", "convenio");
                });

            modelBuilder.Entity("WebApolice.Modulos.Convenio.src.WebApolice.Modulos.Convenio.Infrastructure.Persistence.Models.SiapeOrgao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<string>("Nome")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("siape_orgao_pkey");

                    b.HasIndex(new[] { "LegadoId" }, "ux_siape_orgao_legado")
                        .IsUnique()
                        .HasFilter("(legado_id IS NOT NULL)");

                    b.ToTable("siape_orgao", "convenio");
                });

            modelBuilder.Entity("WebApolice.Modulos.Convenio.src.WebApolice.Modulos.Convenio.Infrastructure.Persistence.Models.SiapeParametro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("CalculoParametro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("calculo_parametro");

                    b.Property<string>("Cgc")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cgc");

                    b.Property<string>("CgcLimpo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cgc_limpo");

                    b.Property<string>("Comando")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("comando");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("CustoLinha")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("custo_linha");

                    b.Property<string>("Empresa")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("empresa");

                    b.Property<int?>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<string>("Rubrica")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rubrica");

                    b.HasKey("Id")
                        .HasName("siape_parametro_pkey");

                    b.HasIndex(new[] { "LegadoId" }, "ux_siape_parametro_legado")
                        .IsUnique()
                        .HasFilter("(legado_id IS NOT NULL)");

                    b.ToTable("siape_parametro", "convenio");
                });

            modelBuilder.Entity("WebApolice.Modulos.Convenio.src.WebApolice.Modulos.Convenio.Infrastructure.Persistence.Models.SiapeCliente", b =>
                {
                    b.HasOne("WebApolice.Modulos.Convenio.src.WebApolice.Modulos.Convenio.Infrastructure.Persistence.Models.SiapeOrgao", "Orgao")
                        .WithMany("SiapeClientes")
                        .HasForeignKey("OrgaoId")
                        .HasConstraintName("siape_cliente_orgao_id_fkey");

                    b.Navigation("Orgao");
                });

            modelBuilder.Entity("WebApolice.Modulos.Convenio.src.WebApolice.Modulos.Convenio.Infrastructure.Persistence.Models.SiapeOrgao", b =>
                {
                    b.Navigation("SiapeClientes");
                });
#pragma warning restore 612, 618
        }
    }
}
