START TRANSACTION;
CREATE TABLE seguro.ramo (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL,
    codigo character varying(50) NOT NULL,
    nome character varying(150) NOT NULL,
    descricao character varying(500),
    ativo boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_ramo PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ux_ramo_public_id ON seguro.ramo (public_id);

ALTER TABLE seguro.apolice_ramo ADD ramo_id bigint NOT NULL DEFAULT 0;


                -- Inserir os ramos únicos a partir dos dados existentes
                INSERT INTO seguro.ramo (public_id, codigo, nome, ativo, created_at, updated_at)
                SELECT gen_random_uuid(), tipo_ramo, tipo_ramo, true, now(), now()
                FROM (
                    SELECT DISTINCT tipo_ramo 
                    FROM seguro.apolice_ramo 
                    WHERE tipo_ramo IS NOT NULL AND tipo_ramo <> ''
                ) AS u;

                -- Atualizar a chave estrangeira na tabela apolice_ramo
                UPDATE seguro.apolice_ramo ar
                SET ramo_id = r.id
                FROM seguro.ramo r
                WHERE ar.tipo_ramo = r.codigo;
            

DROP INDEX seguro.ix_apolice_ramo_tipo_ramo;

DROP INDEX seguro.ux_apolice_ramo_ativo;

ALTER TABLE seguro.apolice_ramo DROP COLUMN tipo_ramo;

CREATE INDEX ix_apolice_ramo_ramo ON seguro.apolice_ramo (ramo_id);

CREATE UNIQUE INDEX ux_apolice_ramo_ativo ON seguro.apolice_ramo (apolice_id, ramo_id) WHERE ativo = true;

ALTER TABLE seguro.apolice_ramo ADD CONSTRAINT fk_apolice_ramo_ramo_ramo_id FOREIGN KEY (ramo_id) REFERENCES seguro.ramo (id) ON DELETE RESTRICT;

INSERT INTO seguro."__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260819023234_AdicionarCadastroGlobalRamo', '10.0.11');

COMMIT;

