CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'seguranca') THEN
        CREATE SCHEMA seguranca;
    END IF;
END $EF$;

CREATE TABLE seguranca.modulo (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    codigo character varying(100) NOT NULL,
    nome character varying(150) NOT NULL,
    descricao character varying(500),
    icone character varying(100),
    ordem integer NOT NULL DEFAULT 0,
    ativo boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT pk_modulo PRIMARY KEY (id)
);

CREATE TABLE seguranca.perfil (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    codigo character varying(100) NOT NULL,
    nome character varying(150) NOT NULL,
    descricao character varying(500),
    perfil_sistema boolean NOT NULL DEFAULT FALSE,
    acesso_total boolean NOT NULL DEFAULT FALSE,
    ativo boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT pk_perfil PRIMARY KEY (id)
);

CREATE TABLE seguranca.usuario (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    keycloak_sub character varying(100) NOT NULL,
    username character varying(100),
    nome character varying(150),
    email character varying(150),
    ativo boolean NOT NULL DEFAULT TRUE,
    ultimo_login_em timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

CREATE TABLE seguranca.recurso (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    modulo_id bigint NOT NULL,
    codigo character varying(100) NOT NULL,
    nome character varying(150) NOT NULL,
    descricao character varying(500),
    rota_frontend character varying(255),
    ordem integer NOT NULL DEFAULT 0,
    ativo boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT pk_recurso PRIMARY KEY (id),
    CONSTRAINT fk_recurso_modulo_modulo_id FOREIGN KEY (modulo_id) REFERENCES seguranca.modulo (id) ON DELETE RESTRICT
);

CREATE TABLE seguranca.usuario_perfil (
    usuario_id bigint NOT NULL,
    perfil_id bigint NOT NULL,
    atribuido_por_usuario_id bigint,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT pk_usuario_perfil PRIMARY KEY (usuario_id, perfil_id),
    CONSTRAINT fk_usuario_perfil_perfil_perfil_id FOREIGN KEY (perfil_id) REFERENCES seguranca.perfil (id) ON DELETE RESTRICT,
    CONSTRAINT fk_usuario_perfil_usuario_atribuido_por_usuario_id FOREIGN KEY (atribuido_por_usuario_id) REFERENCES seguranca.usuario (id) ON DELETE SET NULL,
    CONSTRAINT fk_usuario_perfil_usuario_usuario_id FOREIGN KEY (usuario_id) REFERENCES seguranca.usuario (id) ON DELETE RESTRICT
);

CREATE TABLE seguranca.permissao (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    recurso_id bigint NOT NULL,
    codigo character varying(100) NOT NULL,
    nome character varying(150) NOT NULL,
    descricao character varying(500),
    ativo boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT pk_permissao PRIMARY KEY (id),
    CONSTRAINT fk_permissao_recursos_recurso_id FOREIGN KEY (recurso_id) REFERENCES seguranca.recurso (id) ON DELETE RESTRICT
);

CREATE TABLE seguranca.auditoria_permissao (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid NOT NULL DEFAULT (gen_random_uuid()),
    usuario_executor_id bigint,
    acao character varying(50) NOT NULL,
    entidade_tipo character varying(50) NOT NULL,
    entidade_id bigint NOT NULL,
    usuario_afetado_id bigint,
    perfil_id bigint,
    permissao_id bigint,
    dados_anteriores jsonb,
    dados_novos jsonb,
    motivo character varying(500),
    ip_origem character varying(45),
    user_agent character varying(255),
    correlation_id character varying(100),
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT pk_auditoria_permissao PRIMARY KEY (id),
    CONSTRAINT fk_auditoria_permissao_perfis_perfil_id FOREIGN KEY (perfil_id) REFERENCES seguranca.perfil (id) ON DELETE RESTRICT,
    CONSTRAINT fk_auditoria_permissao_permissoes_permissao_id FOREIGN KEY (permissao_id) REFERENCES seguranca.permissao (id) ON DELETE RESTRICT,
    CONSTRAINT fk_auditoria_permissao_usuarios_usuario_afetado_id FOREIGN KEY (usuario_afetado_id) REFERENCES seguranca.usuario (id) ON DELETE RESTRICT,
    CONSTRAINT fk_auditoria_permissao_usuarios_usuario_executor_id FOREIGN KEY (usuario_executor_id) REFERENCES seguranca.usuario (id) ON DELETE RESTRICT
);

CREATE TABLE seguranca.perfil_permissao (
    perfil_id bigint NOT NULL,
    permissao_id bigint NOT NULL,
    atribuido_por_usuario_id bigint,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT pk_perfil_permissao PRIMARY KEY (perfil_id, permissao_id),
    CONSTRAINT fk_perfil_permissao_perfil_perfil_id FOREIGN KEY (perfil_id) REFERENCES seguranca.perfil (id) ON DELETE RESTRICT,
    CONSTRAINT fk_perfil_permissao_permissoes_permissao_id FOREIGN KEY (permissao_id) REFERENCES seguranca.permissao (id) ON DELETE RESTRICT,
    CONSTRAINT fk_perfil_permissao_usuarios_atribuido_por_usuario_id FOREIGN KEY (atribuido_por_usuario_id) REFERENCES seguranca.usuario (id) ON DELETE SET NULL
);

CREATE INDEX ix_auditoria_permissao_acao ON seguranca.auditoria_permissao (acao);

CREATE INDEX ix_auditoria_permissao_correlation_id ON seguranca.auditoria_permissao (correlation_id);

CREATE INDEX ix_auditoria_permissao_created_at ON seguranca.auditoria_permissao (created_at);

CREATE INDEX ix_auditoria_permissao_perfil_id ON seguranca.auditoria_permissao (perfil_id);

CREATE INDEX ix_auditoria_permissao_permissao_id ON seguranca.auditoria_permissao (permissao_id);

CREATE UNIQUE INDEX ix_auditoria_permissao_public_id ON seguranca.auditoria_permissao (public_id);

CREATE INDEX ix_auditoria_permissao_usuario_afetado_id ON seguranca.auditoria_permissao (usuario_afetado_id);

CREATE INDEX ix_auditoria_permissao_usuario_executor_id ON seguranca.auditoria_permissao (usuario_executor_id);

CREATE UNIQUE INDEX ix_modulo_codigo ON seguranca.modulo (codigo);

CREATE UNIQUE INDEX ix_modulo_public_id ON seguranca.modulo (public_id);

CREATE UNIQUE INDEX ix_perfil_codigo ON seguranca.perfil (codigo);

CREATE UNIQUE INDEX ix_perfil_public_id ON seguranca.perfil (public_id);

CREATE INDEX ix_perfil_permissao_atribuido_por_usuario_id ON seguranca.perfil_permissao (atribuido_por_usuario_id);

CREATE INDEX ix_perfil_permissao_permissao_id ON seguranca.perfil_permissao (permissao_id);

CREATE UNIQUE INDEX ix_permissao_codigo ON seguranca.permissao (codigo);

CREATE UNIQUE INDEX ix_permissao_public_id ON seguranca.permissao (public_id);

CREATE INDEX ix_permissao_recurso_id ON seguranca.permissao (recurso_id);

CREATE UNIQUE INDEX ix_recurso_modulo_id_codigo ON seguranca.recurso (modulo_id, codigo);

CREATE UNIQUE INDEX ix_recurso_public_id ON seguranca.recurso (public_id);

CREATE UNIQUE INDEX ix_usuario_keycloak_sub ON seguranca.usuario (keycloak_sub);

CREATE UNIQUE INDEX ix_usuario_public_id ON seguranca.usuario (public_id);

CREATE INDEX ix_usuario_perfil_atribuido_por_usuario_id ON seguranca.usuario_perfil (atribuido_por_usuario_id);

CREATE INDEX ix_usuario_perfil_perfil_id ON seguranca.usuario_perfil (perfil_id);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260722215747_InicialSeguranca', '10.0.9');

COMMIT;

START TRANSACTION;

                INSERT INTO seguranca.modulo (public_id, codigo, nome, descricao, icone, ordem, ativo, created_at, updated_at)
                VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'CADASTRO', 'Cadastros', 'Módulo destinado às rotinas cadastrais do WebApólice', 'users', 10, true, '2026-07-23 00:00:00Z', '2026-07-23 00:00:00Z');
            


                INSERT INTO seguranca.recurso (public_id, modulo_id, codigo, nome, descricao, rota_frontend, ordem, ativo, created_at, updated_at)
                SELECT 'b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a22', m.id, 'CLIENTES', 'Clientes', 'Cadastro e gerenciamento de clientes', '/clientes', 10, true, '2026-07-23 00:00:00Z', '2026-07-23 00:00:00Z'
                FROM seguranca.modulo m
                WHERE m.codigo = 'CADASTRO';
            


                INSERT INTO seguranca.permissao (public_id, recurso_id, codigo, nome, descricao, ativo, created_at, updated_at)
                SELECT 'c1eebc99-9c0b-4ef8-bb6d-6bb9bd380a31', r.id, 'clientes.visualizar', 'Visualizar clientes', 'Permite consultar a listagem e os detalhes dos clientes', true, '2026-07-23 00:00:00Z', '2026-07-23 00:00:00Z'
                FROM seguranca.recurso r WHERE r.codigo = 'CLIENTES';

                INSERT INTO seguranca.permissao (public_id, recurso_id, codigo, nome, descricao, ativo, created_at, updated_at)
                SELECT 'c2eebc99-9c0b-4ef8-bb6d-6bb9bd380a32', r.id, 'clientes.inserir', 'Inserir clientes', 'Permite cadastrar novos clientes', true, '2026-07-23 00:00:00Z', '2026-07-23 00:00:00Z'
                FROM seguranca.recurso r WHERE r.codigo = 'CLIENTES';

                INSERT INTO seguranca.permissao (public_id, recurso_id, codigo, nome, descricao, ativo, created_at, updated_at)
                SELECT 'c3eebc99-9c0b-4ef8-bb6d-6bb9bd380a33', r.id, 'clientes.alterar', 'Alterar clientes', 'Permite alterar os dados cadastrais dos clientes', true, '2026-07-23 00:00:00Z', '2026-07-23 00:00:00Z'
                FROM seguranca.recurso r WHERE r.codigo = 'CLIENTES';

                INSERT INTO seguranca.permissao (public_id, recurso_id, codigo, nome, descricao, ativo, created_at, updated_at)
                SELECT 'c4eebc99-9c0b-4ef8-bb6d-6bb9bd380a34', r.id, 'clientes.inativar', 'Inativar clientes', 'Permite inativar clientes sem exclusão física', true, '2026-07-23 00:00:00Z', '2026-07-23 00:00:00Z'
                FROM seguranca.recurso r WHERE r.codigo = 'CLIENTES';

                INSERT INTO seguranca.permissao (public_id, recurso_id, codigo, nome, descricao, ativo, created_at, updated_at)
                SELECT 'c5eebc99-9c0b-4ef8-bb6d-6bb9bd380a35', r.id, 'clientes.reativar', 'Reativar clientes', 'Permite reativar clientes anteriormente inativados', true, '2026-07-23 00:00:00Z', '2026-07-23 00:00:00Z'
                FROM seguranca.recurso r WHERE r.codigo = 'CLIENTES';
            


                INSERT INTO seguranca.perfil (public_id, codigo, nome, descricao, perfil_sistema, acesso_total, ativo, created_at, updated_at)
                VALUES 
                ('d1eebc99-9c0b-4ef8-bb6d-6bb9bd380a41', 'ADMINISTRADOR', 'Administrador', 'Perfil interno com acesso total ao WebApólice', true, true, true, '2026-07-23 00:00:00Z', '2026-07-23 00:00:00Z'),
                ('d2eebc99-9c0b-4ef8-bb6d-6bb9bd380a42', 'ADMINISTRATIVO', 'Administrativo', 'Perfil destinado às rotinas administrativas da empresa', false, false, true, '2026-07-23 00:00:00Z', '2026-07-23 00:00:00Z');
            


                INSERT INTO seguranca.perfil_permissao (perfil_id, permissao_id, atribuido_por_usuario_id, created_at)
                SELECT perfil.id, permissao.id, NULL, '2026-07-23 00:00:00Z'
                FROM seguranca.perfil perfil
                CROSS JOIN seguranca.permissao permissao
                WHERE perfil.codigo = 'ADMINISTRATIVO'
                  AND permissao.codigo IN (
                      'clientes.visualizar', 
                      'clientes.inserir', 
                      'clientes.alterar', 
                      'clientes.inativar', 
                      'clientes.reativar'
                  );
            

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260723101318_CargaInicialSeguranca', '10.0.9');

COMMIT;

START TRANSACTION;

                INSERT INTO seguranca.modulo (public_id, codigo, nome, descricao, icone, ordem, ativo, created_at, updated_at)
                VALUES ('e1eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'SEGURANCA', 'Segurança', 'Administração de usuários, perfis e permissões do WebApólice', 'shield', 90, true, '2026-07-24 00:00:00Z', '2026-07-24 00:00:00Z');
            


                INSERT INTO seguranca.recurso (public_id, modulo_id, codigo, nome, descricao, rota_frontend, ordem, ativo, created_at, updated_at)
                SELECT 'e2eebc99-9c0b-4ef8-bb6d-6bb9bd380a21', m.id, 'USUARIOS', 'Usuários', 'Gerenciamento de usuários e acessos', '/seguranca/usuarios', 10, true, '2026-07-24 00:00:00Z', '2026-07-24 00:00:00Z'
                FROM seguranca.modulo m WHERE m.codigo = 'SEGURANCA';

                INSERT INTO seguranca.recurso (public_id, modulo_id, codigo, nome, descricao, rota_frontend, ordem, ativo, created_at, updated_at)
                SELECT 'e3eebc99-9c0b-4ef8-bb6d-6bb9bd380a22', m.id, 'PERFIS', 'Perfis de Acesso', 'Gerenciamento de perfis e permissões funcionais', '/seguranca/perfis', 20, true, '2026-07-24 00:00:00Z', '2026-07-24 00:00:00Z'
                FROM seguranca.modulo m WHERE m.codigo = 'SEGURANCA';

                INSERT INTO seguranca.recurso (public_id, modulo_id, codigo, nome, descricao, rota_frontend, ordem, ativo, created_at, updated_at)
                SELECT 'e4eebc99-9c0b-4ef8-bb6d-6bb9bd380a23', m.id, 'CATALOGO', 'Catálogo Técnico', 'Visualização do catálogo de módulos e recursos do sistema', '/seguranca/catalogo', 30, true, '2026-07-24 00:00:00Z', '2026-07-24 00:00:00Z'
                FROM seguranca.modulo m WHERE m.codigo = 'SEGURANCA';

                INSERT INTO seguranca.recurso (public_id, modulo_id, codigo, nome, descricao, rota_frontend, ordem, ativo, created_at, updated_at)
                SELECT 'e5eebc99-9c0b-4ef8-bb6d-6bb9bd380a24', m.id, 'AUDITORIA', 'Auditoria de Acesso', 'Histórico de alterações de segurança', '/seguranca/auditoria', 40, true, '2026-07-24 00:00:00Z', '2026-07-24 00:00:00Z'
                FROM seguranca.modulo m WHERE m.codigo = 'SEGURANCA';
            


                INSERT INTO seguranca.permissao (public_id, recurso_id, codigo, nome, descricao, ativo, created_at, updated_at)
                SELECT 'f1eebc99-9c0b-4ef8-bb6d-6bb9bd380a31', r.id, 'seguranca.usuarios.visualizar', 'Visualizar usuários', 'Permite consultar a listagem e os detalhes dos usuários', true, '2026-07-24 00:00:00Z', '2026-07-24 00:00:00Z'
                FROM seguranca.recurso r WHERE r.codigo = 'USUARIOS';

                INSERT INTO seguranca.permissao (public_id, recurso_id, codigo, nome, descricao, ativo, created_at, updated_at)
                SELECT 'f2eebc99-9c0b-4ef8-bb6d-6bb9bd380a32', r.id, 'seguranca.usuarios.inserir', 'Inserir usuários', 'Permite cadastrar novos usuários e definir senha temporária', true, '2026-07-24 00:00:00Z', '2026-07-24 00:00:00Z'
                FROM seguranca.recurso r WHERE r.codigo = 'USUARIOS';

                INSERT INTO seguranca.permissao (public_id, recurso_id, codigo, nome, descricao, ativo, created_at, updated_at)
                SELECT 'f3eebc99-9c0b-4ef8-bb6d-6bb9bd380a33', r.id, 'seguranca.usuarios.alterar', 'Alterar usuários', 'Permite atualizar dados e o status dos usuários', true, '2026-07-24 00:00:00Z', '2026-07-24 00:00:00Z'
                FROM seguranca.recurso r WHERE r.codigo = 'USUARIOS';

                INSERT INTO seguranca.permissao (public_id, recurso_id, codigo, nome, descricao, ativo, created_at, updated_at)
                SELECT 'f4eebc99-9c0b-4ef8-bb6d-6bb9bd380a34', r.id, 'seguranca.perfis.visualizar', 'Visualizar perfis', 'Permite consultar a listagem e detalhes dos perfis de acesso', true, '2026-07-24 00:00:00Z', '2026-07-24 00:00:00Z'
                FROM seguranca.recurso r WHERE r.codigo = 'PERFIS';

                INSERT INTO seguranca.permissao (public_id, recurso_id, codigo, nome, descricao, ativo, created_at, updated_at)
                SELECT 'f5eebc99-9c0b-4ef8-bb6d-6bb9bd380a35', r.id, 'seguranca.perfis.inserir', 'Inserir perfis', 'Permite cadastrar novos perfis de acesso', true, '2026-07-24 00:00:00Z', '2026-07-24 00:00:00Z'
                FROM seguranca.recurso r WHERE r.codigo = 'PERFIS';

                INSERT INTO seguranca.permissao (public_id, recurso_id, codigo, nome, descricao, ativo, created_at, updated_at)
                SELECT 'f6eebc99-9c0b-4ef8-bb6d-6bb9bd380a36', r.id, 'seguranca.perfis.alterar', 'Alterar perfis', 'Permite alterar permissões e dados dos perfis de acesso', true, '2026-07-24 00:00:00Z', '2026-07-24 00:00:00Z'
                FROM seguranca.recurso r WHERE r.codigo = 'PERFIS';

                INSERT INTO seguranca.permissao (public_id, recurso_id, codigo, nome, descricao, ativo, created_at, updated_at)
                SELECT 'f7eebc99-9c0b-4ef8-bb6d-6bb9bd380a37', r.id, 'seguranca.catalogo.visualizar', 'Visualizar catálogo', 'Permite visualizar os módulos e recursos técnicos do sistema', true, '2026-07-24 00:00:00Z', '2026-07-24 00:00:00Z'
                FROM seguranca.recurso r WHERE r.codigo = 'CATALOGO';

                INSERT INTO seguranca.permissao (public_id, recurso_id, codigo, nome, descricao, ativo, created_at, updated_at)
                SELECT 'f8eebc99-9c0b-4ef8-bb6d-6bb9bd380a38', r.id, 'seguranca.auditoria.visualizar', 'Visualizar auditoria', 'Permite consultar a auditoria de acessos e configurações de segurança', true, '2026-07-24 00:00:00Z', '2026-07-24 00:00:00Z'
                FROM seguranca.recurso r WHERE r.codigo = 'AUDITORIA';
            

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260724103424_CargaAdministracaoSeguranca', '10.0.9');

COMMIT;

START TRANSACTION;

                INSERT INTO seguranca.usuario_perfil (usuario_id, perfil_id, created_at)
                SELECT u.id, p.id, NOW()
                FROM seguranca.usuario u
                CROSS JOIN seguranca.perfil p
                WHERE (u.username = 'admin' OR u.email = 'admin@progridai.com')
                  AND p.codigo = 'ADMINISTRADOR'
                  AND NOT EXISTS (
                      SELECT 1 FROM seguranca.usuario_perfil up2 
                      WHERE up2.usuario_id = u.id AND up2.perfil_id = p.id
                  );
            

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260724174536_VinculaAdminUsuario', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE seguranca.modulo ADD habilitado boolean NOT NULL DEFAULT TRUE;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260724194126_AdicionarHabilitacaoModulo', '10.0.9');

COMMIT;

START TRANSACTION;
UPDATE seguranca.modulo SET codigo = 'CLIENTES', nome = 'Clientes', descricao = 'Cadastro e administração de clientes' WHERE codigo = 'CADASTRO';

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260728144458_RenomearModuloCadastroParaClientes', '10.0.9');

COMMIT;

START TRANSACTION;

                INSERT INTO seguranca.modulo (public_id, codigo, nome, descricao, icone, ordem, ativo, created_at, updated_at)
                VALUES ('e0eebc99-9c0b-4ef8-bb6d-6bb9bd380e11', 'ESTIPULANTES', 'Estipulantes', 'Gestão de Estipulantes e Subestipulantes', 'users', 20, true, '2026-08-12 00:00:00Z', '2026-08-12 00:00:00Z');
            


                INSERT INTO seguranca.recurso (public_id, modulo_id, codigo, nome, descricao, rota_frontend, ordem, ativo, created_at, updated_at)
                SELECT 'f1eebc99-9c0b-4ef8-bb6d-6bb9bd380f22', m.id, 'ESTIPULANTES', 'Estipulantes', 'Cadastro de estipulantes', '/estipulantes', 10, true, '2026-08-12 00:00:00Z', '2026-08-12 00:00:00Z'
                FROM seguranca.modulo m
                WHERE m.codigo = 'ESTIPULANTES';
            


                INSERT INTO seguranca.permissao (public_id, recurso_id, codigo, nome, descricao, ativo, created_at, updated_at)
                SELECT 'f2eebc99-9c0b-4ef8-bb6d-6bb9bd380f31', r.id, 'estipulantes.visualizar', 'Visualizar estipulantes', 'Permite consultar a listagem e detalhes', true, '2026-08-12 00:00:00Z', '2026-08-12 00:00:00Z'
                FROM seguranca.recurso r WHERE r.codigo = 'ESTIPULANTES';
            


                INSERT INTO seguranca.perfil_permissao (perfil_id, permissao_id, atribuido_por_usuario_id, created_at)
                SELECT perfil.id, permissao.id, NULL, '2026-08-12 00:00:00Z'
                FROM seguranca.perfil perfil
                CROSS JOIN seguranca.permissao permissao
                WHERE perfil.codigo = 'ADMINISTRATIVO'
                  AND permissao.codigo = 'estipulantes.visualizar';
            

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260812001659_CargaInicialEstipulantes', '10.0.9');

COMMIT;

START TRANSACTION;

                INSERT INTO seguranca.permissao (public_id, recurso_id, codigo, nome, descricao, ativo, created_at, updated_at)
                SELECT 'f3eebc99-9c0b-4ef8-bb6d-6bb9bd380f42', r.id, 'estipulantes.inserir', 'Criar estipulantes', 'Permite cadastrar um novo estipulante', true, '2026-08-12 00:30:00Z', '2026-08-12 00:30:00Z'
                FROM seguranca.recurso r WHERE r.codigo = 'ESTIPULANTES';
            


                INSERT INTO seguranca.perfil_permissao (perfil_id, permissao_id, atribuido_por_usuario_id, created_at)
                SELECT perfil.id, permissao.id, NULL, '2026-08-12 00:30:00Z'
                FROM seguranca.perfil perfil
                CROSS JOIN seguranca.permissao permissao
                WHERE perfil.codigo = 'ADMINISTRATIVO'
                  AND permissao.codigo = 'estipulantes.inserir';
            

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260812003121_CargaPermissaoInserirEstipulantes', '10.0.9');

COMMIT;

START TRANSACTION;

                INSERT INTO seguranca.permissao (public_id, recurso_id, codigo, nome, descricao, ativo, created_at, updated_at)
                SELECT 'f4eebc99-9c0b-4ef8-bb6d-6bb9bd380f53', r.id, 'estipulantes.alterar', 'Alterar estipulantes', 'Permite editar os dados de um estipulante existente', true, '2026-08-12 12:00:00Z', '2026-08-12 12:00:00Z'
                FROM seguranca.recurso r WHERE r.codigo = 'ESTIPULANTES';

                INSERT INTO seguranca.permissao (public_id, recurso_id, codigo, nome, descricao, ativo, created_at, updated_at)
                SELECT 'f5eebc99-9c0b-4ef8-bb6d-6bb9bd380f64', r.id, 'estipulantes.inativar', 'Inativar estipulantes', 'Permite inativar um estipulante', true, '2026-08-12 12:00:00Z', '2026-08-12 12:00:00Z'
                FROM seguranca.recurso r WHERE r.codigo = 'ESTIPULANTES';

                INSERT INTO seguranca.permissao (public_id, recurso_id, codigo, nome, descricao, ativo, created_at, updated_at)
                SELECT 'f6eebc99-9c0b-4ef8-bb6d-6bb9bd380f75', r.id, 'estipulantes.reativar', 'Reativar estipulantes', 'Permite reativar um estipulante', true, '2026-08-12 12:00:00Z', '2026-08-12 12:00:00Z'
                FROM seguranca.recurso r WHERE r.codigo = 'ESTIPULANTES';
            


                INSERT INTO seguranca.perfil_permissao (perfil_id, permissao_id, atribuido_por_usuario_id, created_at)
                SELECT perfil.id, permissao.id, NULL, '2026-08-12 12:00:00Z'
                FROM seguranca.perfil perfil
                CROSS JOIN seguranca.permissao permissao
                WHERE perfil.codigo = 'ADMINISTRATIVO'
                  AND permissao.codigo IN ('estipulantes.alterar', 'estipulantes.inativar', 'estipulantes.reativar');
            

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260812154725_CargaPermissoesFaltantesEstipulantes', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE seguranca.recurso ADD habilitado boolean NOT NULL DEFAULT TRUE;


                INSERT INTO seguranca.recurso (public_id, modulo_id, codigo, nome, descricao, ordem, ativo, habilitado, created_at, updated_at)
                SELECT gen_random_uuid(), id, 'RE', 'RE', 'Registro de Empregado', 10, true, true, now(), now()
                FROM seguranca.modulo
                WHERE codigo = 'CLIENTES';
            

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260813143942_AddRecursoHabilitadoAndRE', '10.0.9');

COMMIT;

