// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApolice.Shared.Infrastructure.Persistence;

#nullable disable

namespace WebApolice.Shared.Infrastructure.Migrations
{
    [DbContext(typeof(InfraestruturaDbContext))]
    partial class InfraestruturaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.AgenciadorMigrationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AgenciadorId")
                        .HasColumnType("bigint")
                        .HasColumnName("agenciador_id");

                    b.Property<long?>("CoordenadorId")
                        .HasColumnType("bigint")
                        .HasColumnName("coordenador_id");

                    b.Property<string>("CpfLimpo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cpf_limpo");

                    b.Property<string>("CpfOriginal")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cpf_original");

                    b.Property<bool>("CpfValido")
                        .HasColumnType("boolean")
                        .HasColumnName("cpf_valido");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CriterioMigracao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criterio_migracao");

                    b.Property<int>("LegadoAgenciadorId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_agenciador_id");

                    b.Property<int?>("LegadoCoordenadorId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_coordenador_id");

                    b.Property<string>("NomeOriginal")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_original");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.HasKey("Id")
                        .HasName("agenciador_migration_map_pkey");

                    b.HasIndex(new[] { "LegadoAgenciadorId" }, "agenciador_migration_map_legado_agenciador_id_key")
                        .IsUnique()
                        .HasDatabaseName("ix_agenciador_migration_map_legado_agenciador_id");

                    b.HasIndex(new[] { "AgenciadorId" }, "ix_agenciador_map_agenciador")
                        .HasDatabaseName("ix_agenciador_migration_map_agenciador_id");

                    b.HasIndex(new[] { "CpfLimpo" }, "ix_agenciador_map_cpf")
                        .HasDatabaseName("ix_agenciador_migration_map_cpf_limpo");

                    b.HasIndex(new[] { "PessoaId" }, "ix_agenciador_map_pessoa")
                        .HasDatabaseName("ix_agenciador_migration_map_pessoa_id");

                    b.ToTable("agenciador_migration_map", "legado");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.AgenciamentoCorretoraLancamentoMigrationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AgenciamentoCorretoraLancamentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("agenciamento_corretora_lancamento_id");

                    b.Property<long?>("CorretoraId")
                        .HasColumnType("bigint")
                        .HasColumnName("corretora_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CriterioMigracao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criterio_migracao");

                    b.Property<int>("LegadoAgenciamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_agenciamento_id");

                    b.Property<int?>("LegadoCorretoraId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_corretora_id");

                    b.Property<int?>("LegadoMovimentoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_movimento_id");

                    b.Property<int?>("LegadoPropostaId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_proposta_id");

                    b.Property<long?>("MovimentoTipoId")
                        .HasColumnType("bigint")
                        .HasColumnName("movimento_tipo_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<long?>("PropostaId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_id");

                    b.HasKey("Id")
                        .HasName("agenciamento_corretora_lancamento_migration_map_pkey");

                    b.HasIndex(new[] { "LegadoAgenciamentoId" }, "agenciamento_corretora_lancamento_mi_legado_agenciamento_id_key")
                        .IsUnique()
                        .HasDatabaseName("ix_agenciamento_corretora_lancamento_migration_map_legado_agen");

                    b.HasIndex(new[] { "CorretoraId" }, "ix_agenciamento_corretora_map_corretora")
                        .HasDatabaseName("ix_agenciamento_corretora_lancamento_migration_map_corretora_id");

                    b.HasIndex(new[] { "PropostaId" }, "ix_agenciamento_corretora_map_proposta")
                        .HasDatabaseName("ix_agenciamento_corretora_lancamento_migration_map_proposta_id");

                    b.ToTable("agenciamento_corretora_lancamento_migration_map", "legado");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.ClienteMigrationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<long?>("ClienteVinculoId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_vinculo_id");

                    b.Property<string>("CpfLimpo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cpf_limpo");

                    b.Property<string>("CpfOriginal")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cpf_original");

                    b.Property<bool>("CpfValido")
                        .HasColumnType("boolean")
                        .HasColumnName("cpf_valido");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CriterioCriacaoVinculo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("criterio_criacao_vinculo");

                    b.Property<string>("CriterioUnificacaoPessoa")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("criterio_unificacao_pessoa");

                    b.Property<int>("LegadoClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_cliente_id");

                    b.Property<string>("MatriculaOriginal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("matricula_original");

                    b.Property<string>("NomeOriginal")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_original");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.HasKey("Id")
                        .HasName("cliente_migration_map_pkey");

                    b.HasIndex(new[] { "LegadoClienteId" }, "cliente_migration_map_legado_cliente_id_key")
                        .IsUnique()
                        .HasDatabaseName("ix_cliente_migration_map_legado_cliente_id");

                    b.HasIndex(new[] { "ClienteId" }, "ix_cliente_migration_map_cliente")
                        .HasDatabaseName("ix_cliente_migration_map_cliente_id");

                    b.HasIndex(new[] { "CpfLimpo" }, "ix_cliente_migration_map_cpf")
                        .HasDatabaseName("ix_cliente_migration_map_cpf_limpo");

                    b.HasIndex(new[] { "PessoaId" }, "ix_cliente_migration_map_pessoa")
                        .HasDatabaseName("ix_cliente_migration_map_pessoa_id");

                    b.ToTable("cliente_migration_map", "legado");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.CoberturaMigrationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CoberturaId")
                        .HasColumnType("bigint")
                        .HasColumnName("cobertura_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("LegadoCoberturaId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_cobertura_id");

                    b.Property<string>("NomeOriginal")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_original");

                    b.HasKey("Id")
                        .HasName("cobertura_migration_map_pkey");

                    b.HasIndex(new[] { "LegadoCoberturaId" }, "cobertura_migration_map_legado_cobertura_id_key")
                        .IsUnique()
                        .HasDatabaseName("ix_cobertura_migration_map_legado_cobertura_id");

                    b.ToTable("cobertura_migration_map", "legado");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.CorretoraMigrationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CorretoraId")
                        .HasColumnType("bigint")
                        .HasColumnName("corretora_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CriterioMigracao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criterio_migracao");

                    b.Property<int>("LegadoCorretoraId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_corretora_id");

                    b.Property<string>("NomeOriginal")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_original");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.HasKey("Id")
                        .HasName("corretora_migration_map_pkey");

                    b.HasIndex(new[] { "LegadoCorretoraId" }, "corretora_migration_map_legado_corretora_id_key")
                        .IsUnique()
                        .HasDatabaseName("ix_corretora_migration_map_legado_corretora_id");

                    b.HasIndex(new[] { "CorretoraId" }, "ix_corretora_map_corretora")
                        .HasDatabaseName("ix_corretora_migration_map_corretora_id");

                    b.ToTable("corretora_migration_map", "legado");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.DocumentoAnexoMigrationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ArquivoId")
                        .HasColumnType("bigint")
                        .HasColumnName("arquivo_id");

                    b.Property<string>("ArquivoOriginal")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("arquivo_original");

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CriterioMigracao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criterio_migracao");

                    b.Property<long?>("EstipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("estipulante_id");

                    b.Property<string>("ExtensaoOriginal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("extensao_original");

                    b.Property<int>("LegadoDocumentoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_documento_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<int?>("PkCliente")
                        .HasColumnType("integer")
                        .HasColumnName("pk_cliente");

                    b.Property<int?>("PkEstipulante")
                        .HasColumnType("integer")
                        .HasColumnName("pk_estipulante");

                    b.Property<int?>("PkProposta")
                        .HasColumnType("integer")
                        .HasColumnName("pk_proposta");

                    b.Property<int?>("PkProtocolo")
                        .HasColumnType("integer")
                        .HasColumnName("pk_protocolo");

                    b.Property<int?>("PkSinistro")
                        .HasColumnType("integer")
                        .HasColumnName("pk_sinistro");

                    b.Property<long?>("PropostaId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_id");

                    b.Property<long?>("SinistroId")
                        .HasColumnType("bigint")
                        .HasColumnName("sinistro_id");

                    b.Property<string>("TipoAnexoOriginal")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tipo_anexo_original");

                    b.Property<string>("TituloOriginal")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("titulo_original");

                    b.HasKey("Id")
                        .HasName("documento_anexo_migration_map_pkey");

                    b.HasIndex(new[] { "LegadoDocumentoId" }, "documento_anexo_migration_map_legado_documento_id_key")
                        .IsUnique()
                        .HasDatabaseName("ix_documento_anexo_migration_map_legado_documento_id");

                    b.HasIndex(new[] { "ArquivoId" }, "ix_documento_anexo_map_arquivo")
                        .HasDatabaseName("ix_documento_anexo_migration_map_arquivo_id");

                    b.HasIndex(new[] { "ClienteId" }, "ix_documento_anexo_map_cliente")
                        .HasDatabaseName("ix_documento_anexo_migration_map_cliente_id");

                    b.HasIndex(new[] { "EstipulanteId" }, "ix_documento_anexo_map_estipulante")
                        .HasDatabaseName("ix_documento_anexo_migration_map_estipulante_id");

                    b.HasIndex(new[] { "PropostaId" }, "ix_documento_anexo_map_proposta")
                        .HasDatabaseName("ix_documento_anexo_migration_map_proposta_id");

                    b.HasIndex(new[] { "SinistroId" }, "ix_documento_anexo_map_sinistro")
                        .HasDatabaseName("ix_documento_anexo_migration_map_sinistro_id");

                    b.ToTable("documento_anexo_migration_map", "legado");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.EstipulanteMigrationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CnpjLimpo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cnpj_limpo");

                    b.Property<string>("CnpjOriginal")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cnpj_original");

                    b.Property<bool>("CnpjValido")
                        .HasColumnType("boolean")
                        .HasColumnName("cnpj_valido");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CriterioUnificacaoPessoa")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("criterio_unificacao_pessoa");

                    b.Property<long>("EstipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("estipulante_id");

                    b.Property<int>("LegadoEstipulanteId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_estipulante_id");

                    b.Property<string>("NomeOriginal")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_original");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.HasKey("Id")
                        .HasName("estipulante_migration_map_pkey");

                    b.HasIndex(new[] { "LegadoEstipulanteId" }, "estipulante_migration_map_legado_estipulante_id_key")
                        .IsUnique()
                        .HasDatabaseName("ix_estipulante_migration_map_legado_estipulante_id");

                    b.HasIndex(new[] { "CnpjLimpo" }, "ix_estipulante_migration_map_cnpj")
                        .HasDatabaseName("ix_estipulante_migration_map_cnpj_limpo");

                    b.HasIndex(new[] { "PessoaId" }, "ix_estipulante_migration_map_pessoa")
                        .HasDatabaseName("ix_estipulante_migration_map_pessoa_id");

                    b.ToTable("estipulante_migration_map", "legado");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.MovimentoPropostaMigrationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Classificacao")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("classificacao");

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<long?>("ClienteVinculoId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_vinculo_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CriterioMigracao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criterio_migracao");

                    b.Property<long?>("EstipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("estipulante_id");

                    b.Property<long?>("LancamentoComissaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("lancamento_comissao_id");

                    b.Property<int?>("LegadoClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_cliente_id");

                    b.Property<int?>("LegadoEstipulanteId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_estipulante_id");

                    b.Property<int?>("LegadoMovimentoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_movimento_id");

                    b.Property<int>("LegadoMovimentoPropostaId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_movimento_proposta_id");

                    b.Property<int?>("LegadoPropostaId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_proposta_id");

                    b.Property<long?>("MovimentoTipoId")
                        .HasColumnType("bigint")
                        .HasColumnName("movimento_tipo_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<long?>("PropostaId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_id");

                    b.Property<long>("PropostaMovimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_movimento_id");

                    b.Property<long?>("TituloId")
                        .HasColumnType("bigint")
                        .HasColumnName("titulo_id");

                    b.Property<long?>("TituloPagamentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("titulo_pagamento_id");

                    b.Property<long?>("TituloRetornoBancarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("titulo_retorno_bancario_id");

                    b.HasKey("Id")
                        .HasName("movimento_proposta_migration_map_pkey");

                    b.HasIndex(new[] { "ClienteId" }, "ix_movimento_proposta_map_cliente")
                        .HasDatabaseName("ix_movimento_proposta_migration_map_cliente_id");

                    b.HasIndex(new[] { "EstipulanteId" }, "ix_movimento_proposta_map_estipulante")
                        .HasDatabaseName("ix_movimento_proposta_migration_map_estipulante_id");

                    b.HasIndex(new[] { "PropostaMovimentoId" }, "ix_movimento_proposta_map_movimento")
                        .HasDatabaseName("ix_movimento_proposta_migration_map_proposta_movimento_id");

                    b.HasIndex(new[] { "PropostaId" }, "ix_movimento_proposta_map_proposta")
                        .HasDatabaseName("ix_movimento_proposta_migration_map_proposta_id");

                    b.HasIndex(new[] { "TituloId" }, "ix_movimento_proposta_map_titulo")
                        .HasDatabaseName("ix_movimento_proposta_migration_map_titulo_id");

                    b.HasIndex(new[] { "LegadoMovimentoPropostaId" }, "movimento_proposta_migration_m_legado_movimento_proposta_id_key")
                        .IsUnique()
                        .HasDatabaseName("ix_movimento_proposta_migration_map_legado_movimento_proposta_");

                    b.ToTable("movimento_proposta_migration_map", "legado");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.PlanoMigrationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("LegadoPlanoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_plano_id");

                    b.Property<string>("NomeOriginal")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_original");

                    b.Property<long>("PlanoId")
                        .HasColumnType("bigint")
                        .HasColumnName("plano_id");

                    b.HasKey("Id")
                        .HasName("plano_migration_map_pkey");

                    b.HasIndex(new[] { "LegadoPlanoId" }, "plano_migration_map_legado_plano_id_key")
                        .IsUnique()
                        .HasDatabaseName("ix_plano_migration_map_legado_plano_id");

                    b.ToTable("plano_migration_map", "legado");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.ProdutoMigrationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoReferenciaOriginal")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("codigo_referencia_original");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("LegadoProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_produto_id");

                    b.Property<long>("ProdutoId")
                        .HasColumnType("bigint")
                        .HasColumnName("produto_id");

                    b.HasKey("Id")
                        .HasName("produto_migration_map_pkey");

                    b.HasIndex(new[] { "LegadoProdutoId" }, "produto_migration_map_legado_produto_id_key")
                        .IsUnique()
                        .HasDatabaseName("ix_produto_migration_map_legado_produto_id");

                    b.ToTable("produto_migration_map", "legado");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.PropostaBeneficiarioMigrationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CpfLimpo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cpf_limpo");

                    b.Property<string>("CpfOriginal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cpf_original");

                    b.Property<bool>("CpfValido")
                        .HasColumnType("boolean")
                        .HasColumnName("cpf_valido");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CriterioMigracao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criterio_migracao");

                    b.Property<int>("LegadoBeneficiarioId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_beneficiario_id");

                    b.Property<int?>("LegadoPropostaId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_proposta_id");

                    b.Property<string>("NomeOriginal")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_original");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<string>("ParentescoNormalizado")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("parentesco_normalizado");

                    b.Property<string>("ParentescoOriginal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parentesco_original");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<long>("PropostaBeneficiarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_beneficiario_id");

                    b.Property<long?>("PropostaId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_id");

                    b.HasKey("Id")
                        .HasName("proposta_beneficiario_migration_map_pkey");

                    b.HasIndex(new[] { "CpfLimpo" }, "ix_proposta_beneficiario_map_cpf")
                        .HasDatabaseName("ix_proposta_beneficiario_migration_map_cpf_limpo");

                    b.HasIndex(new[] { "PessoaId" }, "ix_proposta_beneficiario_map_pessoa")
                        .HasDatabaseName("ix_proposta_beneficiario_migration_map_pessoa_id");

                    b.HasIndex(new[] { "PropostaId" }, "ix_proposta_beneficiario_map_proposta")
                        .HasDatabaseName("ix_proposta_beneficiario_migration_map_proposta_id");

                    b.HasIndex(new[] { "LegadoBeneficiarioId" }, "proposta_beneficiario_migration_map_legado_beneficiario_id_key")
                        .IsUnique()
                        .HasDatabaseName("ix_proposta_beneficiario_migration_map_legado_beneficiario_id");

                    b.ToTable("proposta_beneficiario_migration_map", "legado");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.PropostaCoberturaMigrationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CoberturaId")
                        .HasColumnType("bigint")
                        .HasColumnName("cobertura_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CriterioMigracao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criterio_migracao");

                    b.Property<int?>("LegadoCoberturaId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_cobertura_id");

                    b.Property<int>("LegadoPropostaCoberturaId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_proposta_cobertura_id");

                    b.Property<int?>("LegadoPropostaId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_proposta_id");

                    b.Property<int?>("LegadoPropostaTipoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_proposta_tipo_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<long>("PropostaCoberturaId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_cobertura_id");

                    b.Property<long?>("PropostaId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_id");

                    b.Property<long?>("PropostaItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_item_id");

                    b.HasKey("Id")
                        .HasName("proposta_cobertura_migration_map_pkey");

                    b.HasIndex(new[] { "PropostaItemId" }, "ix_proposta_cobertura_migration_map_item")
                        .HasDatabaseName("ix_proposta_cobertura_migration_map_proposta_item_id");

                    b.HasIndex(new[] { "PropostaId" }, "ix_proposta_cobertura_migration_map_proposta")
                        .HasDatabaseName("ix_proposta_cobertura_migration_map_proposta_id");

                    b.HasIndex(new[] { "LegadoPropostaCoberturaId" }, "proposta_cobertura_migration_m_legado_proposta_cobertura_id_key")
                        .IsUnique()
                        .HasDatabaseName("ix_proposta_cobertura_migration_map_legado_proposta_cobertura_");

                    b.ToTable("proposta_cobertura_migration_map", "legado");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.PropostaItemMigrationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CriterioMigracao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criterio_migracao");

                    b.Property<string>("LegadoPlanoOriginal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("legado_plano_original");

                    b.Property<int?>("LegadoProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_produto_id");

                    b.Property<int?>("LegadoPropostaId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_proposta_id");

                    b.Property<int>("LegadoPropostaTipoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_proposta_tipo_id");

                    b.Property<int?>("LegadoTabelaId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_tabela_id");

                    b.Property<int?>("LegadoTipoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_tipo_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<long?>("PlanoId")
                        .HasColumnType("bigint")
                        .HasColumnName("plano_id");

                    b.Property<long?>("ProdutoId")
                        .HasColumnType("bigint")
                        .HasColumnName("produto_id");

                    b.Property<long?>("PropostaId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_id");

                    b.Property<long>("PropostaItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_item_id");

                    b.Property<long?>("TabelaPrecoId")
                        .HasColumnType("bigint")
                        .HasColumnName("tabela_preco_id");

                    b.Property<long?>("TipoProdutoId")
                        .HasColumnType("bigint")
                        .HasColumnName("tipo_produto_id");

                    b.HasKey("Id")
                        .HasName("proposta_item_migration_map_pkey");

                    b.HasIndex(new[] { "PropostaItemId" }, "ix_proposta_item_migration_map_item")
                        .HasDatabaseName("ix_proposta_item_migration_map_proposta_item_id");

                    b.HasIndex(new[] { "PropostaId" }, "ix_proposta_item_migration_map_proposta")
                        .HasDatabaseName("ix_proposta_item_migration_map_proposta_id");

                    b.HasIndex(new[] { "LegadoPropostaTipoId" }, "proposta_item_migration_map_legado_proposta_tipo_id_key")
                        .IsUnique()
                        .HasDatabaseName("ix_proposta_item_migration_map_legado_proposta_tipo_id");

                    b.ToTable("proposta_item_migration_map", "legado");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.PropostaMigrationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<long?>("ClienteVinculoId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_vinculo_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CriterioMigracao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criterio_migracao");

                    b.Property<long?>("EstipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("estipulante_id");

                    b.Property<int?>("LegadoClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_cliente_id");

                    b.Property<int?>("LegadoEstipulanteId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_estipulante_id");

                    b.Property<int>("LegadoPropostaId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_proposta_id");

                    b.Property<int?>("LegadoStatus")
                        .HasColumnType("integer")
                        .HasColumnName("legado_status");

                    b.Property<int?>("LegadoSubestipulanteId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_subestipulante_id");

                    b.Property<string>("NumeroOriginal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_original");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<long>("PropostaId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_id");

                    b.Property<short?>("StatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("status_id");

                    b.Property<long?>("SubestipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("subestipulante_id");

                    b.HasKey("Id")
                        .HasName("proposta_migration_map_pkey");

                    b.HasIndex(new[] { "ClienteId" }, "ix_proposta_migration_map_cliente")
                        .HasDatabaseName("ix_proposta_migration_map_cliente_id");

                    b.HasIndex(new[] { "EstipulanteId" }, "ix_proposta_migration_map_estipulante")
                        .HasDatabaseName("ix_proposta_migration_map_estipulante_id");

                    b.HasIndex(new[] { "PropostaId" }, "ix_proposta_migration_map_proposta")
                        .HasDatabaseName("ix_proposta_migration_map_proposta_id");

                    b.HasIndex(new[] { "ClienteVinculoId" }, "ix_proposta_migration_map_vinculo")
                        .HasDatabaseName("ix_proposta_migration_map_cliente_vinculo_id");

                    b.HasIndex(new[] { "LegadoPropostaId" }, "proposta_migration_map_legado_proposta_id_key")
                        .IsUnique()
                        .HasDatabaseName("ix_proposta_migration_map_legado_proposta_id");

                    b.ToTable("proposta_migration_map", "legado");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.PropostaParticipanteMigrationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AgenciadorId")
                        .HasColumnType("bigint")
                        .HasColumnName("agenciador_id");

                    b.Property<string>("CampoOrigem")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("campo_origem");

                    b.Property<int?>("CodigoLegadoParticipante")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_legado_participante");

                    b.Property<long?>("CorretoraId")
                        .HasColumnType("bigint")
                        .HasColumnName("corretora_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CriterioMigracao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criterio_migracao");

                    b.Property<int?>("LegadoPropostaId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_proposta_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<string>("ParticipanteTipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("participante_tipo");

                    b.Property<long?>("PropostaId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_id");

                    b.Property<long>("PropostaParticipanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_participante_id");

                    b.HasKey("Id")
                        .HasName("proposta_participante_migration_map_pkey");

                    b.HasIndex(new[] { "AgenciadorId" }, "ix_proposta_participante_map_agenciador")
                        .HasDatabaseName("ix_proposta_participante_migration_map_agenciador_id");

                    b.HasIndex(new[] { "CorretoraId" }, "ix_proposta_participante_map_corretora")
                        .HasDatabaseName("ix_proposta_participante_migration_map_corretora_id");

                    b.HasIndex(new[] { "PropostaId" }, "ix_proposta_participante_map_proposta")
                        .HasDatabaseName("ix_proposta_participante_migration_map_proposta_id");

                    b.ToTable("proposta_participante_migration_map", "legado");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.ProtocoloAcompanhamentoMigrationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CriterioMigracao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criterio_migracao");

                    b.Property<int>("LegadoAcompanhamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_acompanhamento_id");

                    b.Property<int?>("LegadoProtocoloId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_protocolo_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<long>("ProtocoloAcompanhamentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("protocolo_acompanhamento_id");

                    b.Property<long?>("ProtocoloLoteId")
                        .HasColumnType("bigint")
                        .HasColumnName("protocolo_lote_id");

                    b.HasKey("Id")
                        .HasName("protocolo_acompanhamento_migration_map_pkey");

                    b.HasIndex(new[] { "ProtocoloLoteId" }, "ix_protocolo_acompanhamento_map_lote")
                        .HasDatabaseName("ix_protocolo_acompanhamento_migration_map_protocolo_lote_id");

                    b.HasIndex(new[] { "LegadoAcompanhamentoId" }, "protocolo_acompanhamento_migration_legado_acompanhamento_id_key")
                        .IsUnique()
                        .HasDatabaseName("ix_protocolo_acompanhamento_migration_map_legado_acompanhament");

                    b.ToTable("protocolo_acompanhamento_migration_map", "legado");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.ProtocoloItemMigrationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<long?>("ClienteVinculoId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_vinculo_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CriterioMigracao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criterio_migracao");

                    b.Property<long?>("EstipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("estipulante_id");

                    b.Property<int?>("LegadoClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_cliente_id");

                    b.Property<int>("LegadoClienteProtocoloId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_cliente_protocolo_id");

                    b.Property<int?>("LegadoEstipulanteId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_estipulante_id");

                    b.Property<int?>("LegadoProtocoloId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_protocolo_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<string>("OrigemLegado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("origem_legado");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<long>("ProtocoloItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("protocolo_item_id");

                    b.Property<long?>("ProtocoloLoteId")
                        .HasColumnType("bigint")
                        .HasColumnName("protocolo_lote_id");

                    b.HasKey("Id")
                        .HasName("protocolo_item_migration_map_pkey");

                    b.HasIndex(new[] { "ClienteId" }, "ix_protocolo_item_map_cliente")
                        .HasDatabaseName("ix_protocolo_item_migration_map_cliente_id");

                    b.HasIndex(new[] { "ProtocoloItemId" }, "ix_protocolo_item_map_item")
                        .HasDatabaseName("ix_protocolo_item_migration_map_protocolo_item_id");

                    b.HasIndex(new[] { "ProtocoloLoteId" }, "ix_protocolo_item_map_lote")
                        .HasDatabaseName("ix_protocolo_item_migration_map_protocolo_lote_id");

                    b.HasIndex(new[] { "OrigemLegado", "LegadoClienteProtocoloId" }, "protocolo_item_migration_map_origem_legado_legado_cliente_p_key")
                        .IsUnique()
                        .HasDatabaseName("ix_protocolo_item_migration_map_origem_legado_legado_cliente_p");

                    b.ToTable("protocolo_item_migration_map", "legado");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.ProtocoloLoteMigrationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CriterioMigracao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criterio_migracao");

                    b.Property<DateTime?>("DataProtocoloOriginal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_protocolo_original");

                    b.Property<int>("LegadoProtocoloId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_protocolo_id");

                    b.Property<int?>("NumeroProtocoloOriginal")
                        .HasColumnType("integer")
                        .HasColumnName("numero_protocolo_original");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<long>("ProtocoloLoteId")
                        .HasColumnType("bigint")
                        .HasColumnName("protocolo_lote_id");

                    b.HasKey("Id")
                        .HasName("protocolo_lote_migration_map_pkey");

                    b.HasIndex(new[] { "ProtocoloLoteId" }, "ix_protocolo_lote_map_lote")
                        .HasDatabaseName("ix_protocolo_lote_migration_map_protocolo_lote_id");

                    b.HasIndex(new[] { "LegadoProtocoloId" }, "protocolo_lote_migration_map_legado_protocolo_id_key")
                        .IsUnique()
                        .HasDatabaseName("ix_protocolo_lote_migration_map_legado_protocolo_id");

                    b.ToTable("protocolo_lote_migration_map", "legado");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.SinistroAcompanhamentoMigrationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AcompanhamentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("acompanhamento_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CriterioMigracao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criterio_migracao");

                    b.Property<int>("LegadoAcompanhamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_acompanhamento_id");

                    b.Property<int?>("LegadoSinistroId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_sinistro_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<long?>("SinistroId")
                        .HasColumnType("bigint")
                        .HasColumnName("sinistro_id");

                    b.HasKey("Id")
                        .HasName("sinistro_acompanhamento_migration_map_pkey");

                    b.HasIndex(new[] { "SinistroId" }, "ix_sinistro_acompanhamento_map_sinistro")
                        .HasDatabaseName("ix_sinistro_acompanhamento_migration_map_sinistro_id");

                    b.HasIndex(new[] { "LegadoAcompanhamentoId" }, "sinistro_acompanhamento_migration__legado_acompanhamento_id_key")
                        .IsUnique()
                        .HasDatabaseName("ix_sinistro_acompanhamento_migration_map_legado_acompanhamento");

                    b.ToTable("sinistro_acompanhamento_migration_map", "legado");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.SinistroMigrationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<long?>("ClienteVinculoId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_vinculo_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CriterioMigracao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criterio_migracao");

                    b.Property<int?>("LegadoPropostaId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_proposta_id");

                    b.Property<int>("LegadoSinistroId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_sinistro_id");

                    b.Property<int?>("LegadoStatus")
                        .HasColumnType("integer")
                        .HasColumnName("legado_status");

                    b.Property<string>("NumeroSinistroOriginal")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("numero_sinistro_original");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<long?>("PropostaId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_id");

                    b.Property<long>("SinistroId")
                        .HasColumnType("bigint")
                        .HasColumnName("sinistro_id");

                    b.Property<short?>("StatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("status_id");

                    b.HasKey("Id")
                        .HasName("sinistro_migration_map_pkey");

                    b.HasIndex(new[] { "ClienteId" }, "ix_sinistro_migration_map_cliente")
                        .HasDatabaseName("ix_sinistro_migration_map_cliente_id");

                    b.HasIndex(new[] { "PropostaId" }, "ix_sinistro_migration_map_proposta")
                        .HasDatabaseName("ix_sinistro_migration_map_proposta_id");

                    b.HasIndex(new[] { "SinistroId" }, "ix_sinistro_migration_map_sinistro")
                        .HasDatabaseName("ix_sinistro_migration_map_sinistro_id");

                    b.HasIndex(new[] { "LegadoSinistroId" }, "sinistro_migration_map_legado_sinistro_id_key")
                        .IsUnique()
                        .HasDatabaseName("ix_sinistro_migration_map_legado_sinistro_id");

                    b.ToTable("sinistro_migration_map", "legado");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.TabelaPrecoMigrationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("LegadoTabelaId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_tabela_id");

                    b.Property<string>("NomeOriginal")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_original");

                    b.Property<long>("TabelaPrecoId")
                        .HasColumnType("bigint")
                        .HasColumnName("tabela_preco_id");

                    b.HasKey("Id")
                        .HasName("tabela_preco_migration_map_pkey");

                    b.HasIndex(new[] { "LegadoTabelaId" }, "tabela_preco_migration_map_legado_tabela_id_key")
                        .IsUnique()
                        .HasDatabaseName("ix_tabela_preco_migration_map_legado_tabela_id");

                    b.ToTable("tabela_preco_migration_map", "legado");
                });

            modelBuilder.Entity("WebApolice.Shared.Infrastructure.Persistence.Models.TipoProdutoMigrationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("LegadoTipoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_tipo_id");

                    b.Property<string>("NomeOriginal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_original");

                    b.Property<long>("TipoProdutoId")
                        .HasColumnType("bigint")
                        .HasColumnName("tipo_produto_id");

                    b.HasKey("Id")
                        .HasName("tipo_produto_migration_map_pkey");

                    b.HasIndex(new[] { "LegadoTipoId" }, "tipo_produto_migration_map_legado_tipo_id_key")
                        .IsUnique()
                        .HasDatabaseName("ix_tipo_produto_migration_map_legado_tipo_id");

                    b.ToTable("tipo_produto_migration_map", "legado");
                });
#pragma warning restore 612, 618
        }
    }
}
