// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApolice.Modulos.Seguranca.Infrastructure.Persistence;

#nullable disable

namespace WebApolice.Modulos.Seguranca.Infrastructure.Migrations
{
    [DbContext(typeof(SegurancaDbContext))]
    [Migration("20260813215625_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApolice.Modulos.Seguranca.Domain.Auditoria.AuditoriaPermissao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("acao");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DadosAnteriores")
                        .HasColumnType("jsonb")
                        .HasColumnName("dados_anteriores");

                    b.Property<string>("DadosNovos")
                        .HasColumnType("jsonb")
                        .HasColumnName("dados_novos");

                    b.Property<long>("EntidadeId")
                        .HasColumnType("bigint")
                        .HasColumnName("entidade_id");

                    b.Property<string>("EntidadeTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entidade_tipo");

                    b.Property<string>("IpOrigem")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_origem");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo");

                    b.Property<long?>("PerfilId")
                        .HasColumnType("bigint")
                        .HasColumnName("perfil_id");

                    b.Property<long?>("PermissaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("permissao_id");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_agent");

                    b.Property<long?>("UsuarioAfetadoId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_afetado_id");

                    b.Property<long?>("UsuarioExecutorId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_executor_id");

                    b.HasKey("Id")
                        .HasName("pk_auditoria_permissao");

                    b.HasIndex("Acao")
                        .HasDatabaseName("ix_auditoria_permissao_acao");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_auditoria_permissao_correlation_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_auditoria_permissao_created_at");

                    b.HasIndex("PerfilId")
                        .HasDatabaseName("ix_auditoria_permissao_perfil_id");

                    b.HasIndex("PermissaoId")
                        .HasDatabaseName("ix_auditoria_permissao_permissao_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_auditoria_permissao_public_id");

                    b.HasIndex("UsuarioAfetadoId")
                        .HasDatabaseName("ix_auditoria_permissao_usuario_afetado_id");

                    b.HasIndex("UsuarioExecutorId")
                        .HasDatabaseName("ix_auditoria_permissao_usuario_executor_id");

                    b.ToTable("auditoria_permissao", "seguranca");
                });

            modelBuilder.Entity("WebApolice.Modulos.Seguranca.Domain.Modulo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<bool>("Habilitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("habilitado");

                    b.Property<string>("Icone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("ordem");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_modulo");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_modulo_codigo");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_modulo_public_id");

                    b.ToTable("modulo", "seguranca");
                });

            modelBuilder.Entity("WebApolice.Modulos.Seguranca.Domain.Perfil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AcessoTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("acesso_total");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<bool>("PerfilSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("perfil_sistema");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_perfil");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_perfil_codigo");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_perfil_public_id");

                    b.ToTable("perfil", "seguranca");
                });

            modelBuilder.Entity("WebApolice.Modulos.Seguranca.Domain.Permissao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("RecursoId")
                        .HasColumnType("bigint")
                        .HasColumnName("recurso_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_permissao");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_permissao_codigo");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_permissao_public_id");

                    b.HasIndex("RecursoId")
                        .HasDatabaseName("ix_permissao_recurso_id");

                    b.ToTable("permissao", "seguranca");
                });

            modelBuilder.Entity("WebApolice.Modulos.Seguranca.Domain.Recurso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<bool>("Habilitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("habilitado");

                    b.Property<long>("ModuloId")
                        .HasColumnType("bigint")
                        .HasColumnName("modulo_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("ordem");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("RotaFrontend")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("rota_frontend");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_recurso");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_recurso_public_id");

                    b.HasIndex("ModuloId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_recurso_modulo_id_codigo");

                    b.ToTable("recurso", "seguranca");
                });

            modelBuilder.Entity("WebApolice.Modulos.Seguranca.Domain.Relacionamentos.PerfilPermissao", b =>
                {
                    b.Property<long>("PerfilId")
                        .HasColumnType("bigint")
                        .HasColumnName("perfil_id");

                    b.Property<long>("PermissaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("permissao_id");

                    b.Property<long?>("AtribuidoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("atribuido_por_usuario_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PerfilId", "PermissaoId")
                        .HasName("pk_perfil_permissao");

                    b.HasIndex("AtribuidoPorUsuarioId")
                        .HasDatabaseName("ix_perfil_permissao_atribuido_por_usuario_id");

                    b.HasIndex("PermissaoId")
                        .HasDatabaseName("ix_perfil_permissao_permissao_id");

                    b.ToTable("perfil_permissao", "seguranca");
                });

            modelBuilder.Entity("WebApolice.Modulos.Seguranca.Domain.Relacionamentos.UsuarioPerfil", b =>
                {
                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.Property<long>("PerfilId")
                        .HasColumnType("bigint")
                        .HasColumnName("perfil_id");

                    b.Property<long?>("AtribuidoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("atribuido_por_usuario_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UsuarioId", "PerfilId")
                        .HasName("pk_usuario_perfil");

                    b.HasIndex("AtribuidoPorUsuarioId")
                        .HasDatabaseName("ix_usuario_perfil_atribuido_por_usuario_id");

                    b.HasIndex("PerfilId")
                        .HasDatabaseName("ix_usuario_perfil_perfil_id");

                    b.ToTable("usuario_perfil", "seguranca");
                });

            modelBuilder.Entity("WebApolice.Modulos.Seguranca.Domain.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("KeycloakSub")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("keycloak_sub");

                    b.Property<string>("Nome")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("UltimoLoginEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_login_em");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("KeycloakSub")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_keycloak_sub");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_public_id");

                    b.ToTable("usuario", "seguranca");
                });

            modelBuilder.Entity("WebApolice.Modulos.Seguranca.Domain.Auditoria.AuditoriaPermissao", b =>
                {
                    b.HasOne("WebApolice.Modulos.Seguranca.Domain.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_auditoria_permissao_perfis_perfil_id");

                    b.HasOne("WebApolice.Modulos.Seguranca.Domain.Permissao", "Permissao")
                        .WithMany()
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_auditoria_permissao_permissoes_permissao_id");

                    b.HasOne("WebApolice.Modulos.Seguranca.Domain.Usuario", "UsuarioAfetado")
                        .WithMany()
                        .HasForeignKey("UsuarioAfetadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_auditoria_permissao_usuarios_usuario_afetado_id");

                    b.HasOne("WebApolice.Modulos.Seguranca.Domain.Usuario", "UsuarioExecutor")
                        .WithMany()
                        .HasForeignKey("UsuarioExecutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_auditoria_permissao_usuarios_usuario_executor_id");

                    b.Navigation("Perfil");

                    b.Navigation("Permissao");

                    b.Navigation("UsuarioAfetado");

                    b.Navigation("UsuarioExecutor");
                });

            modelBuilder.Entity("WebApolice.Modulos.Seguranca.Domain.Permissao", b =>
                {
                    b.HasOne("WebApolice.Modulos.Seguranca.Domain.Recurso", "Recurso")
                        .WithMany("Permissoes")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_permissao_recursos_recurso_id");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("WebApolice.Modulos.Seguranca.Domain.Recurso", b =>
                {
                    b.HasOne("WebApolice.Modulos.Seguranca.Domain.Modulo", "Modulo")
                        .WithMany("Recursos")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recurso_modulo_modulo_id");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("WebApolice.Modulos.Seguranca.Domain.Relacionamentos.PerfilPermissao", b =>
                {
                    b.HasOne("WebApolice.Modulos.Seguranca.Domain.Usuario", "AtribuidoPorUsuario")
                        .WithMany()
                        .HasForeignKey("AtribuidoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_perfil_permissao_usuarios_atribuido_por_usuario_id");

                    b.HasOne("WebApolice.Modulos.Seguranca.Domain.Perfil", "Perfil")
                        .WithMany("Permissoes")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_perfil_permissao_perfil_perfil_id");

                    b.HasOne("WebApolice.Modulos.Seguranca.Domain.Permissao", "Permissao")
                        .WithMany()
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_perfil_permissao_permissoes_permissao_id");

                    b.Navigation("AtribuidoPorUsuario");

                    b.Navigation("Perfil");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("WebApolice.Modulos.Seguranca.Domain.Relacionamentos.UsuarioPerfil", b =>
                {
                    b.HasOne("WebApolice.Modulos.Seguranca.Domain.Usuario", "AtribuidoPorUsuario")
                        .WithMany()
                        .HasForeignKey("AtribuidoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_usuario_perfil_usuario_atribuido_por_usuario_id");

                    b.HasOne("WebApolice.Modulos.Seguranca.Domain.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_perfil_perfil_perfil_id");

                    b.HasOne("WebApolice.Modulos.Seguranca.Domain.Usuario", "Usuario")
                        .WithMany("Perfis")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_perfil_usuario_usuario_id");

                    b.Navigation("AtribuidoPorUsuario");

                    b.Navigation("Perfil");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebApolice.Modulos.Seguranca.Domain.Modulo", b =>
                {
                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("WebApolice.Modulos.Seguranca.Domain.Perfil", b =>
                {
                    b.Navigation("Permissoes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("WebApolice.Modulos.Seguranca.Domain.Recurso", b =>
                {
                    b.Navigation("Permissoes");
                });

            modelBuilder.Entity("WebApolice.Modulos.Seguranca.Domain.Usuario", b =>
                {
                    b.Navigation("Perfis");
                });
#pragma warning restore 612, 618
        }
    }
}
