DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'financeiro') THEN
        CREATE SCHEMA financeiro;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS financeiro."__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM financeiro."__EFMigrationsHistory" WHERE "migration_id" = '20261006224700_CriarConveniosCobranca') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'financeiro') THEN
            CREATE SCHEMA financeiro;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM financeiro."__EFMigrationsHistory" WHERE "migration_id" = '20261006224700_CriarConveniosCobranca') THEN
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
    CREATE EXTENSION IF NOT EXISTS pgcrypto;
    CREATE EXTENSION IF NOT EXISTS unaccent;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM financeiro."__EFMigrationsHistory" WHERE "migration_id" = '20261006224700_CriarConveniosCobranca') THEN
    CREATE TABLE financeiro.convenio_cobranca (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        public_id uuid NOT NULL DEFAULT (gen_random_uuid()),
        ativo boolean NOT NULL DEFAULT TRUE,
        banco_id bigint,
        nome character varying(150) NOT NULL,
        agencia character varying(30),
        conta_corrente character varying(30),
        nome_empresa character varying(150),
        codigo_empresa character varying(80),
        numero_arquivo integer,
        nome_inicial_arquivo character varying(80),
        extensao_arquivo character varying(10),
        layout_arquivo smallint,
        local_remessa_arquivo text,
        local_retorno_arquivo text,
        comunica_vindi boolean,
        observacao text,
        legado_id integer,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        updated_at timestamp with time zone NOT NULL DEFAULT (now()),
        inscricao_estadual character varying(40),
        est_endereco character varying(150),
        est_numero character varying(100),
        est_bairro character varying(100),
        est_complemento character varying(100),
        est_cep character varying(20),
        est_cidade character varying(100),
        est_uf character varying(4),
        est_nome character varying(120),
        CONSTRAINT convenio_cobranca_pkey PRIMARY KEY (id),
        CONSTRAINT fk_convenio_cobranca_banco FOREIGN KEY (banco_id) REFERENCES core.banco (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM financeiro."__EFMigrationsHistory" WHERE "migration_id" = '20261006224700_CriarConveniosCobranca') THEN
    CREATE INDEX ix_convenio_cobranca_banco_id ON financeiro.convenio_cobranca (banco_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM financeiro."__EFMigrationsHistory" WHERE "migration_id" = '20261006224700_CriarConveniosCobranca') THEN
    CREATE UNIQUE INDEX ix_convenio_cobranca_legado_id ON financeiro.convenio_cobranca (legado_id) WHERE (legado_id IS NOT NULL);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM financeiro."__EFMigrationsHistory" WHERE "migration_id" = '20261006224700_CriarConveniosCobranca') THEN
    CREATE UNIQUE INDEX ix_convenio_cobranca_public_id ON financeiro.convenio_cobranca (public_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM financeiro."__EFMigrationsHistory" WHERE "migration_id" = '20261006224700_CriarConveniosCobranca') THEN
    INSERT INTO financeiro."__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20261006224700_CriarConveniosCobranca', '10.0.11');
    END IF;
END $EF$;
COMMIT;
