// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApolice.Modulos.Comissao.src.WebApolice.Modulos.Comissao.Infrastructure.Persistence;

#nullable disable

namespace WebApolice.Modulos.Comissao.Infrastructure.Migrations
{
    [DbContext(typeof(ComissaoDbContext))]
    partial class ComissaoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApolice.Modulos.Comissao.src.WebApolice.Modulos.Comissao.Infrastructure.Persistence.Models.AgenciadorComissaoConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AgenciadorId")
                        .HasColumnType("bigint")
                        .HasColumnName("agenciador_id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("FimVigencia")
                        .HasColumnType("date")
                        .HasColumnName("fim_vigencia");

                    b.Property<DateOnly?>("InicioVigencia")
                        .HasColumnType("date")
                        .HasColumnName("inicio_vigencia");

                    b.Property<int?>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("origem")
                        .HasDefaultValueSql("'legado'::character varying");

                    b.Property<decimal?>("PercentualPadrao")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("percentual_padrao");

                    b.Property<decimal?>("PercentualRepasse")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("percentual_repasse");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("agenciador_comissao_config_pkey");

                    b.HasIndex(new[] { "AgenciadorId" }, "ix_agenciador_comissao_config_agenciador");

                    b.HasIndex(new[] { "InicioVigencia", "FimVigencia" }, "ix_agenciador_comissao_config_vigencia");

                    b.HasIndex(new[] { "LegadoId" }, "ux_agenciador_comissao_config_legado")
                        .IsUnique()
                        .HasFilter("(legado_id IS NOT NULL)");

                    b.ToTable("agenciador_comissao_config", "comissao");
                });

            modelBuilder.Entity("WebApolice.Modulos.Comissao.src.WebApolice.Modulos.Comissao.Infrastructure.Persistence.Models.AgenciamentoCorretoraLancamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CorretoraId")
                        .HasColumnType("bigint")
                        .HasColumnName("corretora_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataCadastro")
                        .HasColumnType("date")
                        .HasColumnName("data_cadastro");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date")
                        .HasColumnName("data_pagamento");

                    b.Property<DateOnly?>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<bool?>("GerouFatura")
                        .HasColumnType("boolean")
                        .HasColumnName("gerou_fatura");

                    b.Property<int?>("LegadoCorretoraId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_corretora_id");

                    b.Property<int>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<int?>("LegadoMovimentoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_movimento_id");

                    b.Property<int?>("LegadoPropostaId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_proposta_id");

                    b.Property<long?>("MovimentoTipoId")
                        .HasColumnType("bigint")
                        .HasColumnName("movimento_tipo_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<int?>("ParcelaFinal")
                        .HasColumnType("integer")
                        .HasColumnName("parcela_final");

                    b.Property<int?>("ParcelaInicial")
                        .HasColumnType("integer")
                        .HasColumnName("parcela_inicial");

                    b.Property<decimal?>("Percentual")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("percentual");

                    b.Property<long?>("PropostaId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_id");

                    b.Property<int?>("StatusLegado")
                        .HasColumnType("integer")
                        .HasColumnName("status_legado");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("ValorAgenciamento")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_agenciamento");

                    b.Property<decimal?>("ValorPago")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_pago");

                    b.Property<decimal?>("ValorPremio")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_premio");

                    b.HasKey("Id")
                        .HasName("agenciamento_corretora_lancamento_pkey");

                    b.HasIndex(new[] { "CorretoraId" }, "ix_agenciamento_corretora_lancamento_corretora");

                    b.HasIndex(new[] { "MovimentoTipoId" }, "ix_agenciamento_corretora_lancamento_movimento");

                    b.HasIndex(new[] { "DataPagamento" }, "ix_agenciamento_corretora_lancamento_pagamento")
                        .HasFilter("(data_pagamento IS NOT NULL)");

                    b.HasIndex(new[] { "PropostaId" }, "ix_agenciamento_corretora_lancamento_proposta");

                    b.HasIndex(new[] { "DataVencimento" }, "ix_agenciamento_corretora_lancamento_vencimento");

                    b.HasIndex(new[] { "LegadoId" }, "ux_agenciamento_corretora_lancamento_legado")
                        .IsUnique();

                    b.ToTable("agenciamento_corretora_lancamento", "comissao");
                });

            modelBuilder.Entity("WebApolice.Modulos.Comissao.src.WebApolice.Modulos.Comissao.Infrastructure.Persistence.Models.CorretoraAgenciador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AgenciadorId")
                        .HasColumnType("bigint")
                        .HasColumnName("agenciador_id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<long?>("CorretoraId")
                        .HasColumnType("bigint")
                        .HasColumnName("corretora_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("FimVigencia")
                        .HasColumnType("date")
                        .HasColumnName("fim_vigencia");

                    b.Property<DateOnly?>("InicioVigencia")
                        .HasColumnType("date")
                        .HasColumnName("inicio_vigencia");

                    b.Property<int?>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<decimal?>("PercentualAgenciamento")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("percentual_agenciamento");

                    b.Property<decimal?>("PercentualRepasse")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("percentual_repasse");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("corretora_agenciador_pkey");

                    b.HasIndex(new[] { "AgenciadorId" }, "ix_corretora_agenciador_agenciador");

                    b.HasIndex(new[] { "CorretoraId" }, "ix_corretora_agenciador_corretora");

                    b.HasIndex(new[] { "LegadoId" }, "ux_corretora_agenciador_legado")
                        .IsUnique()
                        .HasFilter("(legado_id IS NOT NULL)");

                    b.ToTable("corretora_agenciador", "comissao");
                });

            modelBuilder.Entity("WebApolice.Modulos.Comissao.src.WebApolice.Modulos.Comissao.Infrastructure.Persistence.Models.EstipulanteComissaoConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AgenciadorId")
                        .HasColumnType("bigint")
                        .HasColumnName("agenciador_id");

                    b.Property<decimal?>("AgenciadorPercentualRepasse")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("agenciador_percentual_repasse");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<int?>("ComissaoApartirParcela")
                        .HasColumnType("integer")
                        .HasColumnName("comissao_apartir_parcela");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("EstipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("estipulante_id");

                    b.Property<decimal?>("PercentualAgenciamento")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("percentual_agenciamento");

                    b.Property<decimal?>("PercentualBonus")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("percentual_bonus");

                    b.Property<decimal?>("PercentualComissao")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("percentual_comissao");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("estipulante_comissao_config_pkey");

                    b.HasIndex(new[] { "AgenciadorId" }, "ix_estipulante_comissao_agenciador");

                    b.HasIndex(new[] { "EstipulanteId" }, "ux_estipulante_comissao_config")
                        .IsUnique();

                    b.ToTable("estipulante_comissao_config", "comissao");
                });

            modelBuilder.Entity("WebApolice.Modulos.Comissao.src.WebApolice.Modulos.Comissao.Infrastructure.Persistence.Models.FaturaComissaoResumo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Ano")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ano");

                    b.Property<int?>("CompetenciaInt")
                        .HasColumnType("integer")
                        .HasColumnName("competencia_int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date")
                        .HasColumnName("data_pagamento");

                    b.Property<long?>("EstipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("estipulante_id");

                    b.Property<int?>("LegadoEstipulanteId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_estipulante_id");

                    b.Property<int>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<string>("Mes")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("mes");

                    b.Property<decimal?>("PremioPagamento")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("premio_pagamento");

                    b.Property<decimal?>("ValorPago")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_pago");

                    b.HasKey("Id")
                        .HasName("fatura_comissao_resumo_pkey");

                    b.HasIndex(new[] { "CompetenciaInt" }, "ix_fatura_comissao_resumo_competencia");

                    b.HasIndex(new[] { "EstipulanteId" }, "ix_fatura_comissao_resumo_estipulante");

                    b.HasIndex(new[] { "LegadoId" }, "ux_fatura_comissao_resumo_legado")
                        .IsUnique();

                    b.ToTable("fatura_comissao_resumo", "comissao");
                });

            modelBuilder.Entity("WebApolice.Modulos.Comissao.src.WebApolice.Modulos.Comissao.Infrastructure.Persistence.Models.FaturaIntegracao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Alterado")
                        .HasColumnType("integer")
                        .HasColumnName("alterado");

                    b.Property<int?>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<int?>("CompetenciaInt")
                        .HasColumnType("integer")
                        .HasColumnName("competencia_int");

                    b.Property<string>("CorretoraCodigoOriginal")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("corretora_codigo_original");

                    b.Property<long?>("CorretoraId")
                        .HasColumnType("bigint")
                        .HasColumnName("corretora_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DataLancamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_lancamento");

                    b.Property<DateOnly?>("DataRecebimento")
                        .HasColumnType("date")
                        .HasColumnName("data_recebimento");

                    b.Property<DateOnly?>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<long?>("EstipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("estipulante_id");

                    b.Property<bool?>("GerouArquivo")
                        .HasColumnType("boolean")
                        .HasColumnName("gerou_arquivo");

                    b.Property<int>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<int?>("Mes")
                        .HasColumnType("integer")
                        .HasColumnName("mes");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<decimal?>("PercentualAgenciamento")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("percentual_agenciamento");

                    b.Property<decimal?>("PercentualCorretagem")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("percentual_corretagem");

                    b.Property<string>("SeguradoraCodigoOriginal")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("seguradora_codigo_original");

                    b.Property<long?>("SeguradoraId")
                        .HasColumnType("bigint")
                        .HasColumnName("seguradora_id");

                    b.Property<int?>("SituacaoLegado")
                        .HasColumnType("integer")
                        .HasColumnName("situacao_legado");

                    b.Property<string>("Tipo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("ValorFatura")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_fatura");

                    b.Property<decimal?>("ValorReceber")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_receber");

                    b.Property<decimal?>("ValorRecebido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_recebido");

                    b.HasKey("Id")
                        .HasName("fatura_integracao_pkey");

                    b.HasIndex(new[] { "Ano", "Mes" }, "ix_fatura_integracao_competencia");

                    b.HasIndex(new[] { "CorretoraId" }, "ix_fatura_integracao_corretora");

                    b.HasIndex(new[] { "EstipulanteId" }, "ix_fatura_integracao_estipulante");

                    b.HasIndex(new[] { "SeguradoraId" }, "ix_fatura_integracao_seguradora");

                    b.HasIndex(new[] { "Tipo", "SituacaoLegado" }, "ix_fatura_integracao_tipo_situacao");

                    b.HasIndex(new[] { "DataVencimento" }, "ix_fatura_integracao_vencimento");

                    b.HasIndex(new[] { "LegadoId" }, "ux_fatura_integracao_legado")
                        .IsUnique();

                    b.ToTable("fatura_integracao", "comissao");
                });

            modelBuilder.Entity("WebApolice.Modulos.Comissao.src.WebApolice.Modulos.Comissao.Infrastructure.Persistence.Models.FaturaVidaAgenciamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoCooperadoOriginal")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo_cooperado_original");

                    b.Property<string>("CodigoCorretoraOriginal")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo_corretora_original");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inclusao");

                    b.Property<DateTime?>("DataRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_registro");

                    b.Property<decimal?>("Iof")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("iof");

                    b.Property<int>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<int?>("LegadoPropostaId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_proposta_id");

                    b.Property<string>("NumeroNf")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("numero_nf");

                    b.Property<string>("OrigemLegado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("origem_legado");

                    b.Property<decimal?>("Premio")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("premio");

                    b.Property<decimal?>("PremioLiquido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("premio_liquido");

                    b.Property<long?>("PropostaId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_id");

                    b.Property<string>("TipoAgenciamento")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tipo_agenciamento");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("ValorAgenciamento")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_agenciamento");

                    b.Property<decimal?>("ValorDiferenca")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_diferenca");

                    b.Property<decimal?>("ValorRecebido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_recebido");

                    b.HasKey("Id")
                        .HasName("fatura_vida_agenciamento_pkey");

                    b.HasIndex(new[] { "DataInclusao" }, "ix_fatura_vida_agenciamento_data_inclusao");

                    b.HasIndex(new[] { "OrigemLegado" }, "ix_fatura_vida_agenciamento_origem");

                    b.HasIndex(new[] { "PropostaId" }, "ix_fatura_vida_agenciamento_proposta");

                    b.HasIndex(new[] { "OrigemLegado", "LegadoId" }, "ux_fatura_vida_agenciamento_legado")
                        .IsUnique();

                    b.ToTable("fatura_vida_agenciamento", "comissao");
                });

            modelBuilder.Entity("WebApolice.Modulos.Comissao.src.WebApolice.Modulos.Comissao.Infrastructure.Persistence.Models.FaturaVidaRecebimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date")
                        .HasColumnName("data_pagamento");

                    b.Property<long?>("EstipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("estipulante_id");

                    b.Property<long?>("FaturaVidaAgenciamentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("fatura_vida_agenciamento_id");

                    b.Property<int?>("LegadoEstipulanteId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_estipulante_id");

                    b.Property<int?>("LegadoFaturaVidaId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_fatura_vida_id");

                    b.Property<int>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<string>("Observacao")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("observacao");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("fatura_vida_recebimento_pkey");

                    b.HasIndex(new[] { "DataPagamento" }, "ix_fatura_vida_recebimento_data");

                    b.HasIndex(new[] { "EstipulanteId" }, "ix_fatura_vida_recebimento_estipulante");

                    b.HasIndex(new[] { "FaturaVidaAgenciamentoId" }, "ix_fatura_vida_recebimento_fatura_vida");

                    b.HasIndex(new[] { "LegadoId" }, "ux_fatura_vida_recebimento_legado")
                        .IsUnique();

                    b.ToTable("fatura_vida_recebimento", "comissao");
                });

            modelBuilder.Entity("WebApolice.Modulos.Comissao.src.WebApolice.Modulos.Comissao.Infrastructure.Persistence.Models.LancamentoComissao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<int?>("CompetenciaAno")
                        .HasColumnType("integer")
                        .HasColumnName("competencia_ano");

                    b.Property<int?>("CompetenciaInt")
                        .HasColumnType("integer")
                        .HasColumnName("competencia_int");

                    b.Property<int?>("CompetenciaMes")
                        .HasColumnType("integer")
                        .HasColumnName("competencia_mes");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("EstipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("estipulante_id");

                    b.Property<char?>("Gerado")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasColumnName("gerado");

                    b.Property<int?>("LegadoMovimentoPropostaId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_movimento_proposta_id");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("origem")
                        .HasDefaultValueSql("'movimento_proposta_legado'::character varying");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<long?>("PropostaId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_id");

                    b.Property<long?>("PropostaMovimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_movimento_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pendente'::character varying");

                    b.Property<long?>("TituloId")
                        .HasColumnType("bigint")
                        .HasColumnName("titulo_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("ValorBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_base");

                    b.Property<decimal?>("ValorBruto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_bruto");

                    b.Property<decimal?>("ValorLiquido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_liquido");

                    b.HasKey("Id")
                        .HasName("lancamento_comissao_pkey");

                    b.HasIndex(new[] { "CompetenciaAno", "CompetenciaMes" }, "ix_lancamento_comissao_competencia");

                    b.HasIndex(new[] { "PropostaMovimentoId" }, "ix_lancamento_comissao_movimento");

                    b.HasIndex(new[] { "PropostaId" }, "ix_lancamento_comissao_proposta");

                    b.HasIndex(new[] { "TituloId" }, "ix_lancamento_comissao_titulo");

                    b.ToTable("lancamento_comissao", "comissao");
                });

            modelBuilder.Entity("WebApolice.Modulos.Comissao.src.WebApolice.Modulos.Comissao.Infrastructure.Persistence.Models.LancamentoFaturaEstipulante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("ComissaoRecebida")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("comissao_recebida");

                    b.Property<int?>("CompetenciaAno")
                        .HasColumnType("integer")
                        .HasColumnName("competencia_ano");

                    b.Property<int?>("CompetenciaInt")
                        .HasColumnType("integer")
                        .HasColumnName("competencia_int");

                    b.Property<int?>("CompetenciaMes")
                        .HasColumnType("integer")
                        .HasColumnName("competencia_mes");

                    b.Property<string>("CompetenciaOriginal")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("competencia_original");

                    b.Property<long?>("CorretoraId")
                        .HasColumnType("bigint")
                        .HasColumnName("corretora_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataRecebimento")
                        .HasColumnType("date")
                        .HasColumnName("data_recebimento");

                    b.Property<DateOnly?>("DataVencimentoFatura")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento_fatura");

                    b.Property<long?>("EstipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("estipulante_id");

                    b.Property<bool?>("LancamentoManual")
                        .HasColumnType("boolean")
                        .HasColumnName("lancamento_manual");

                    b.Property<int?>("LegadoCorretoraId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_corretora_id");

                    b.Property<int?>("LegadoEstipulanteId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_estipulante_id");

                    b.Property<int>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<decimal?>("PercentualCorretagem")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("percentual_corretagem");

                    b.Property<decimal?>("PremioTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("premio_total");

                    b.Property<decimal?>("ValorFaturado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_faturado");

                    b.HasKey("Id")
                        .HasName("lancamento_fatura_estipulante_pkey");

                    b.HasIndex(new[] { "CompetenciaInt" }, "ix_lancamento_fatura_estipulante_competencia");

                    b.HasIndex(new[] { "CorretoraId" }, "ix_lancamento_fatura_estipulante_corretora");

                    b.HasIndex(new[] { "EstipulanteId" }, "ix_lancamento_fatura_estipulante_estipulante");

                    b.HasIndex(new[] { "LegadoId" }, "ux_lancamento_fatura_estipulante_legado")
                        .IsUnique();

                    b.ToTable("lancamento_fatura_estipulante", "comissao");
                });

            modelBuilder.Entity("WebApolice.Modulos.Comissao.src.WebApolice.Modulos.Comissao.Infrastructure.Persistence.Models.PropostaParticipante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AgenciadorId")
                        .HasColumnType("bigint")
                        .HasColumnName("agenciador_id");

                    b.Property<int?>("AgenciamentoParcelaFinal")
                        .HasColumnType("integer")
                        .HasColumnName("agenciamento_parcela_final");

                    b.Property<int?>("AgenciamentoParcelaInicial")
                        .HasColumnType("integer")
                        .HasColumnName("agenciamento_parcela_inicial");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<decimal?>("Bonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("bonus");

                    b.Property<int?>("CarteiraParcelaInicial")
                        .HasColumnType("integer")
                        .HasColumnName("carteira_parcela_inicial");

                    b.Property<string>("CodigoAgenciamento")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("codigo_agenciamento");

                    b.Property<int?>("CodigoLegadoParticipante")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_legado_participante");

                    b.Property<long?>("CorretoraId")
                        .HasColumnType("bigint")
                        .HasColumnName("corretora_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LegadoCampoOrigem")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("legado_campo_origem");

                    b.Property<long?>("ParticipanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("participante_id");

                    b.Property<string>("ParticipanteTipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("participante_tipo");

                    b.Property<decimal?>("PercentualAgenciamento")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("percentual_agenciamento");

                    b.Property<decimal?>("PercentualCarteira")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("percentual_carteira");

                    b.Property<long>("PropostaId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_id");

                    b.HasKey("Id")
                        .HasName("proposta_participante_pkey");

                    b.HasIndex(new[] { "AgenciadorId" }, "ix_proposta_participante_agenciador");

                    b.HasIndex(new[] { "CodigoLegadoParticipante" }, "ix_proposta_participante_codigo_legado");

                    b.HasIndex(new[] { "CorretoraId" }, "ix_proposta_participante_corretora");

                    b.HasIndex(new[] { "PropostaId" }, "ix_proposta_participante_proposta");

                    b.HasIndex(new[] { "ParticipanteTipo" }, "ix_proposta_participante_tipo");

                    b.ToTable("proposta_participante", "comissao");
                });

            modelBuilder.Entity("WebApolice.Modulos.Comissao.src.WebApolice.Modulos.Comissao.Infrastructure.Persistence.Models.FaturaVidaRecebimento", b =>
                {
                    b.HasOne("WebApolice.Modulos.Comissao.src.WebApolice.Modulos.Comissao.Infrastructure.Persistence.Models.FaturaVidaAgenciamento", "FaturaVidaAgenciamento")
                        .WithMany("FaturaVidaRecebimentos")
                        .HasForeignKey("FaturaVidaAgenciamentoId")
                        .HasConstraintName("fatura_vida_recebimento_fatura_vida_agenciamento_id_fkey");

                    b.Navigation("FaturaVidaAgenciamento");
                });

            modelBuilder.Entity("WebApolice.Modulos.Comissao.src.WebApolice.Modulos.Comissao.Infrastructure.Persistence.Models.FaturaVidaAgenciamento", b =>
                {
                    b.Navigation("FaturaVidaRecebimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
