// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApolice.Modulos.Atendimento.src.WebApolice.Modulos.Atendimento.Infrastructure.Persistence;

#nullable disable

namespace WebApolice.Modulos.Atendimento.Infrastructure.Migrations
{
    [DbContext(typeof(AtendimentoDbContext))]
    partial class AtendimentoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApolice.Modulos.Atendimento.src.WebApolice.Modulos.Atendimento.Infrastructure.Persistence.Models.ProtocoloAcompanhamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Contato")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("contato");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataAcompanhamento")
                        .HasColumnType("date")
                        .HasColumnName("data_acompanhamento");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("HoraOriginal")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("hora_original");

                    b.Property<int>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<long?>("ProtocoloLoteId")
                        .HasColumnType("bigint")
                        .HasColumnName("protocolo_lote_id");

                    b.Property<int?>("UsuarioLegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_legado_id");

                    b.HasKey("Id")
                        .HasName("protocolo_acompanhamento_pkey");

                    b.HasIndex(new[] { "DataAcompanhamento" }, "ix_protocolo_acompanhamento_data");

                    b.HasIndex(new[] { "ProtocoloLoteId" }, "ix_protocolo_acompanhamento_lote");

                    b.HasIndex(new[] { "LegadoId" }, "ux_protocolo_acompanhamento_legado")
                        .IsUnique();

                    b.ToTable("protocolo_acompanhamento", "atendimento");
                });

            modelBuilder.Entity("WebApolice.Modulos.Atendimento.src.WebApolice.Modulos.Atendimento.Infrastructure.Persistence.Models.ProtocoloItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<long?>("ClienteVinculoId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_vinculo_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataVigencia")
                        .HasColumnType("date")
                        .HasColumnName("data_vigencia");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Equipe")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("equipe");

                    b.Property<long?>("EstipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("estipulante_id");

                    b.Property<int?>("LegadoClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_cliente_id");

                    b.Property<int?>("LegadoEstipulanteId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_estipulante_id");

                    b.Property<int>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<string>("Matricula")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("matricula");

                    b.Property<string>("NomeConjuge")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_conjuge");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<string>("OrigemLegado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("origem_legado");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<decimal?>("Premio")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("premio");

                    b.Property<long>("ProtocoloLoteId")
                        .HasColumnType("bigint")
                        .HasColumnName("protocolo_lote_id");

                    b.Property<string>("TipoItem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo_item")
                        .HasDefaultValueSql("'titular'::character varying");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("protocolo_item_pkey");

                    b.HasIndex(new[] { "ClienteId" }, "ix_protocolo_item_cliente");

                    b.HasIndex(new[] { "EstipulanteId" }, "ix_protocolo_item_estipulante");

                    b.HasIndex(new[] { "ProtocoloLoteId" }, "ix_protocolo_item_lote");

                    b.HasIndex(new[] { "Matricula" }, "ix_protocolo_item_matricula");

                    b.HasIndex(new[] { "TipoItem" }, "ix_protocolo_item_tipo");

                    b.HasIndex(new[] { "ClienteVinculoId" }, "ix_protocolo_item_vinculo");

                    b.HasIndex(new[] { "OrigemLegado", "LegadoId" }, "ux_protocolo_item_legado_origem")
                        .IsUnique();

                    b.ToTable("protocolo_item", "atendimento");
                });

            modelBuilder.Entity("WebApolice.Modulos.Atendimento.src.WebApolice.Modulos.Atendimento.Infrastructure.Persistence.Models.ProtocoloLote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("AnexoConsultor")
                        .HasColumnType("boolean")
                        .HasColumnName("anexo_consultor");

                    b.Property<bool?>("AnexoSeguradora")
                        .HasColumnType("boolean")
                        .HasColumnName("anexo_seguradora");

                    b.Property<int?>("ConsultorLegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("consultor_legado_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DataProtocolo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_protocolo");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<int?>("NumeroProtocolo")
                        .HasColumnType("integer")
                        .HasColumnName("numero_protocolo");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'ativo'::character varying");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("UsuarioLegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_legado_id");

                    b.HasKey("Id")
                        .HasName("protocolo_lote_pkey");

                    b.HasIndex(new[] { "ConsultorLegadoId" }, "ix_protocolo_lote_consultor");

                    b.HasIndex(new[] { "DataProtocolo" }, "ix_protocolo_lote_data");

                    b.HasIndex(new[] { "NumeroProtocolo" }, "ix_protocolo_lote_numero");

                    b.HasIndex(new[] { "LegadoId" }, "ux_protocolo_lote_legado")
                        .IsUnique();

                    b.ToTable("protocolo_lote", "atendimento");
                });

            modelBuilder.Entity("WebApolice.Modulos.Atendimento.src.WebApolice.Modulos.Atendimento.Infrastructure.Persistence.Models.ProtocoloRelatorioSeguradora", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DataRelatorio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_relatorio");

                    b.Property<int>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.HasKey("Id")
                        .HasName("protocolo_relatorio_seguradora_pkey");

                    b.HasIndex(new[] { "DataRelatorio" }, "ix_protocolo_rel_seg_data");

                    b.HasIndex(new[] { "LegadoId" }, "ux_protocolo_rel_seg_legado")
                        .IsUnique();

                    b.ToTable("protocolo_relatorio_seguradora", "atendimento");
                });

            modelBuilder.Entity("WebApolice.Modulos.Atendimento.src.WebApolice.Modulos.Atendimento.Infrastructure.Persistence.Models.ProtocoloRelatorioSeguradoraItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<long?>("ClienteVinculoId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_vinculo_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("LegadoClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_cliente_id");

                    b.Property<int?>("LegadoProtocoloId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_protocolo_id");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<long?>("ProtocoloLoteId")
                        .HasColumnType("bigint")
                        .HasColumnName("protocolo_lote_id");

                    b.Property<long>("RelatorioId")
                        .HasColumnType("bigint")
                        .HasColumnName("relatorio_id");

                    b.HasKey("Id")
                        .HasName("protocolo_relatorio_seguradora_item_pkey");

                    b.HasIndex(new[] { "ClienteId" }, "ix_protocolo_rel_seg_item_cliente");

                    b.HasIndex(new[] { "ProtocoloLoteId" }, "ix_protocolo_rel_seg_item_protocolo");

                    b.HasIndex(new[] { "RelatorioId" }, "ix_protocolo_rel_seg_item_relatorio");

                    b.ToTable("protocolo_relatorio_seguradora_item", "atendimento");
                });

            modelBuilder.Entity("WebApolice.Modulos.Atendimento.src.WebApolice.Modulos.Atendimento.Infrastructure.Persistence.Models.ProtocoloAcompanhamento", b =>
                {
                    b.HasOne("WebApolice.Modulos.Atendimento.src.WebApolice.Modulos.Atendimento.Infrastructure.Persistence.Models.ProtocoloLote", "ProtocoloLote")
                        .WithMany("ProtocoloAcompanhamentos")
                        .HasForeignKey("ProtocoloLoteId")
                        .HasConstraintName("protocolo_acompanhamento_protocolo_lote_id_fkey");

                    b.Navigation("ProtocoloLote");
                });

            modelBuilder.Entity("WebApolice.Modulos.Atendimento.src.WebApolice.Modulos.Atendimento.Infrastructure.Persistence.Models.ProtocoloItem", b =>
                {
                    b.HasOne("WebApolice.Modulos.Atendimento.src.WebApolice.Modulos.Atendimento.Infrastructure.Persistence.Models.ProtocoloLote", "ProtocoloLote")
                        .WithMany("ProtocoloItems")
                        .HasForeignKey("ProtocoloLoteId")
                        .IsRequired()
                        .HasConstraintName("protocolo_item_protocolo_lote_id_fkey");

                    b.Navigation("ProtocoloLote");
                });

            modelBuilder.Entity("WebApolice.Modulos.Atendimento.src.WebApolice.Modulos.Atendimento.Infrastructure.Persistence.Models.ProtocoloRelatorioSeguradoraItem", b =>
                {
                    b.HasOne("WebApolice.Modulos.Atendimento.src.WebApolice.Modulos.Atendimento.Infrastructure.Persistence.Models.ProtocoloLote", "ProtocoloLote")
                        .WithMany("ProtocoloRelatorioSeguradoraItems")
                        .HasForeignKey("ProtocoloLoteId")
                        .HasConstraintName("protocolo_relatorio_seguradora_item_protocolo_lote_id_fkey");

                    b.HasOne("WebApolice.Modulos.Atendimento.src.WebApolice.Modulos.Atendimento.Infrastructure.Persistence.Models.ProtocoloRelatorioSeguradora", "Relatorio")
                        .WithMany("ProtocoloRelatorioSeguradoraItems")
                        .HasForeignKey("RelatorioId")
                        .IsRequired()
                        .HasConstraintName("protocolo_relatorio_seguradora_item_relatorio_id_fkey");

                    b.Navigation("ProtocoloLote");

                    b.Navigation("Relatorio");
                });

            modelBuilder.Entity("WebApolice.Modulos.Atendimento.src.WebApolice.Modulos.Atendimento.Infrastructure.Persistence.Models.ProtocoloLote", b =>
                {
                    b.Navigation("ProtocoloAcompanhamentos");

                    b.Navigation("ProtocoloItems");

                    b.Navigation("ProtocoloRelatorioSeguradoraItems");
                });

            modelBuilder.Entity("WebApolice.Modulos.Atendimento.src.WebApolice.Modulos.Atendimento.Infrastructure.Persistence.Models.ProtocoloRelatorioSeguradora", b =>
                {
                    b.Navigation("ProtocoloRelatorioSeguradoraItems");
                });
#pragma warning restore 612, 618
        }
    }
}
