// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApolice.Modulos.Sinistros.src.WebApolice.Modulos.Sinistros.Infrastructure.Persistence;

#nullable disable

namespace WebApolice.Modulos.Sinistros.Infrastructure.Migrations
{
    [DbContext(typeof(SinistrosDbContext))]
    partial class SinistrosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApolice.Modulos.Sinistros.src.WebApolice.Modulos.Sinistros.Infrastructure.Persistence.Models.Acompanhamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Contato")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("contato");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataAcompanhamento")
                        .HasColumnType("date")
                        .HasColumnName("data_acompanhamento");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("HoraOriginal")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("hora_original");

                    b.Property<int>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<long?>("SinistroId")
                        .HasColumnType("bigint")
                        .HasColumnName("sinistro_id");

                    b.Property<int?>("UsuarioLegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_legado_id");

                    b.HasKey("Id")
                        .HasName("acompanhamento_pkey");

                    b.HasIndex(new[] { "DataAcompanhamento" }, "ix_sinistro_acompanhamento_data");

                    b.HasIndex(new[] { "SinistroId" }, "ix_sinistro_acompanhamento_sinistro");

                    b.HasIndex(new[] { "LegadoId" }, "ux_sinistro_acompanhamento_legado")
                        .IsUnique();

                    b.ToTable("acompanhamento", "sinistro");
                });

            modelBuilder.Entity("WebApolice.Modulos.Sinistros.src.WebApolice.Modulos.Sinistros.Infrastructure.Persistence.Models.Sinistro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Causa")
                        .HasColumnType("text")
                        .HasColumnName("causa");

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<long?>("ClienteVinculoId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_vinculo_id");

                    b.Property<string>("CpfSinistradoLimpo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cpf_sinistrado_limpo");

                    b.Property<string>("CpfSinistradoOriginal")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cpf_sinistrado_original");

                    b.Property<bool>("CpfSinistradoValido")
                        .HasColumnType("boolean")
                        .HasColumnName("cpf_sinistrado_valido");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataAviso")
                        .HasColumnType("date")
                        .HasColumnName("data_aviso");

                    b.Property<DateTime?>("DataCarta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_carta");

                    b.Property<DateOnly?>("DataEncerramento")
                        .HasColumnType("date")
                        .HasColumnName("data_encerramento");

                    b.Property<DateOnly?>("DataEnvioSeguradora")
                        .HasColumnType("date")
                        .HasColumnName("data_envio_seguradora");

                    b.Property<DateOnly?>("DataOcorrencia")
                        .HasColumnType("date")
                        .HasColumnName("data_ocorrencia");

                    b.Property<DateTime?>("DataProtocolo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_protocolo");

                    b.Property<DateTime?>("DataRegulacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_regulacao");

                    b.Property<DateTime?>("DataRelacaoFamilia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_relacao_familia");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("EstipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("estipulante_id");

                    b.Property<int>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<string>("NumeroSinistro")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("numero_sinistro");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<long>("PropostaId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_id");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long?>("SeguradoraId")
                        .HasColumnType("bigint")
                        .HasColumnName("seguradora_id");

                    b.Property<string>("SituacaoOriginal")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("situacao_original");

                    b.Property<short?>("StatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("status_id");

                    b.Property<int?>("TipoPlanoLegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_plano_legado_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("ValorAuxilioFuneral")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_auxilio_funeral");

                    b.Property<decimal?>("ValorAvisado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_avisado");

                    b.Property<decimal?>("ValorCestaBasica")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_cesta_basica");

                    b.Property<decimal?>("ValorImportancia")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_importancia");

                    b.Property<decimal?>("ValorIndenizacao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_indenizacao");

                    b.HasKey("Id")
                        .HasName("sinistro_pkey");

                    b.HasIndex(new[] { "ClienteId" }, "ix_sinistro_cliente");

                    b.HasIndex(new[] { "CpfSinistradoLimpo" }, "ix_sinistro_cpf_sinistrado");

                    b.HasIndex(new[] { "DataAviso" }, "ix_sinistro_data_aviso");

                    b.HasIndex(new[] { "DataOcorrencia" }, "ix_sinistro_data_ocorrencia");

                    b.HasIndex(new[] { "EstipulanteId" }, "ix_sinistro_estipulante");

                    b.HasIndex(new[] { "PropostaId" }, "ix_sinistro_proposta");

                    b.HasIndex(new[] { "StatusId" }, "ix_sinistro_status");

                    b.HasIndex(new[] { "ClienteVinculoId" }, "ix_sinistro_vinculo");

                    b.HasIndex(new[] { "LegadoId" }, "ux_sinistro_legado")
                        .IsUnique();

                    b.ToTable("sinistro", "sinistro");
                });

            modelBuilder.Entity("WebApolice.Modulos.Sinistros.src.WebApolice.Modulos.Sinistros.Infrastructure.Persistence.Models.SinistroBeneficiario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CpfLimpo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cpf_limpo");

                    b.Property<string>("CpfOriginal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cpf_original");

                    b.Property<bool>("CpfValido")
                        .HasColumnType("boolean")
                        .HasColumnName("cpf_valido");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<string>("Nome")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<string>("ParentescoOriginal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parentesco_original");

                    b.Property<decimal?>("PercentualParticipacao")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("percentual_participacao");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<long?>("PropostaBeneficiarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_beneficiario_id");

                    b.Property<long?>("PropostaId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_id");

                    b.Property<long>("SinistroId")
                        .HasColumnType("bigint")
                        .HasColumnName("sinistro_id");

                    b.Property<decimal?>("ValorPago")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_pago");

                    b.HasKey("Id")
                        .HasName("sinistro_beneficiario_pkey");

                    b.HasIndex(new[] { "CpfLimpo" }, "ix_sinistro_beneficiario_cpf");

                    b.HasIndex(new[] { "PropostaBeneficiarioId" }, "ix_sinistro_beneficiario_proposta_beneficiario");

                    b.HasIndex(new[] { "SinistroId" }, "ix_sinistro_beneficiario_sinistro");

                    b.HasIndex(new[] { "LegadoId" }, "ux_sinistro_beneficiario_legado")
                        .IsUnique()
                        .HasFilter("(legado_id IS NOT NULL)");

                    b.ToTable("sinistro_beneficiario", "sinistro");
                });

            modelBuilder.Entity("WebApolice.Modulos.Sinistros.src.WebApolice.Modulos.Sinistros.Infrastructure.Persistence.Models.SinistroCobertura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CoberturaId")
                        .HasColumnType("bigint")
                        .HasColumnName("cobertura_id");

                    b.Property<int?>("CoberturaSinistroLegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("cobertura_sinistro_legado_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<decimal?>("PremioConjuge")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("premio_conjuge");

                    b.Property<decimal?>("PremioTitular")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("premio_titular");

                    b.Property<long?>("PropostaCoberturaId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_cobertura_id");

                    b.Property<long?>("PropostaId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_id");

                    b.Property<long>("SinistroId")
                        .HasColumnType("bigint")
                        .HasColumnName("sinistro_id");

                    b.Property<decimal?>("ValorEstimado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_estimado");

                    b.Property<decimal?>("ValorPago")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_pago");

                    b.HasKey("Id")
                        .HasName("sinistro_cobertura_pkey");

                    b.HasIndex(new[] { "CoberturaId" }, "ix_sinistro_cobertura_cobertura");

                    b.HasIndex(new[] { "PropostaCoberturaId" }, "ix_sinistro_cobertura_proposta_cobertura");

                    b.HasIndex(new[] { "SinistroId" }, "ix_sinistro_cobertura_sinistro");

                    b.HasIndex(new[] { "CoberturaSinistroLegadoId" }, "ux_sinistro_cobertura_cobertura_legado")
                        .IsUnique()
                        .HasFilter("(cobertura_sinistro_legado_id IS NOT NULL)");

                    b.HasIndex(new[] { "LegadoId" }, "ux_sinistro_cobertura_legado")
                        .IsUnique()
                        .HasFilter("(legado_id IS NOT NULL)");

                    b.ToTable("sinistro_cobertura", "sinistro");
                });

            modelBuilder.Entity("WebApolice.Modulos.Sinistros.src.WebApolice.Modulos.Sinistros.Infrastructure.Persistence.Models.SinistroStatus", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<bool>("Finalizador")
                        .HasColumnType("boolean")
                        .HasColumnName("finalizador");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("sinistro_status_pkey");

                    b.HasIndex(new[] { "Codigo" }, "sinistro_status_codigo_key")
                        .IsUnique();

                    b.ToTable("sinistro_status", "sinistro");
                });

            modelBuilder.Entity("WebApolice.Modulos.Sinistros.src.WebApolice.Modulos.Sinistros.Infrastructure.Persistence.Models.Acompanhamento", b =>
                {
                    b.HasOne("WebApolice.Modulos.Sinistros.src.WebApolice.Modulos.Sinistros.Infrastructure.Persistence.Models.Sinistro", "Sinistro")
                        .WithMany("Acompanhamentos")
                        .HasForeignKey("SinistroId")
                        .HasConstraintName("acompanhamento_sinistro_id_fkey");

                    b.Navigation("Sinistro");
                });

            modelBuilder.Entity("WebApolice.Modulos.Sinistros.src.WebApolice.Modulos.Sinistros.Infrastructure.Persistence.Models.Sinistro", b =>
                {
                    b.HasOne("WebApolice.Modulos.Sinistros.src.WebApolice.Modulos.Sinistros.Infrastructure.Persistence.Models.SinistroStatus", "Status")
                        .WithMany("Sinistros")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("sinistro_status_id_fkey");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("WebApolice.Modulos.Sinistros.src.WebApolice.Modulos.Sinistros.Infrastructure.Persistence.Models.SinistroBeneficiario", b =>
                {
                    b.HasOne("WebApolice.Modulos.Sinistros.src.WebApolice.Modulos.Sinistros.Infrastructure.Persistence.Models.Sinistro", "Sinistro")
                        .WithMany("SinistroBeneficiarios")
                        .HasForeignKey("SinistroId")
                        .IsRequired()
                        .HasConstraintName("sinistro_beneficiario_sinistro_id_fkey");

                    b.Navigation("Sinistro");
                });

            modelBuilder.Entity("WebApolice.Modulos.Sinistros.src.WebApolice.Modulos.Sinistros.Infrastructure.Persistence.Models.SinistroCobertura", b =>
                {
                    b.HasOne("WebApolice.Modulos.Sinistros.src.WebApolice.Modulos.Sinistros.Infrastructure.Persistence.Models.Sinistro", "Sinistro")
                        .WithMany("SinistroCoberturas")
                        .HasForeignKey("SinistroId")
                        .IsRequired()
                        .HasConstraintName("sinistro_cobertura_sinistro_id_fkey");

                    b.Navigation("Sinistro");
                });

            modelBuilder.Entity("WebApolice.Modulos.Sinistros.src.WebApolice.Modulos.Sinistros.Infrastructure.Persistence.Models.Sinistro", b =>
                {
                    b.Navigation("Acompanhamentos");

                    b.Navigation("SinistroBeneficiarios");

                    b.Navigation("SinistroCoberturas");
                });

            modelBuilder.Entity("WebApolice.Modulos.Sinistros.src.WebApolice.Modulos.Sinistros.Infrastructure.Persistence.Models.SinistroStatus", b =>
                {
                    b.Navigation("Sinistros");
                });
#pragma warning restore 612, 618
        }
    }
}
