// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApolice.Modulos.Documentos.src.WebApolice.Modulos.Documentos.Infrastructure.Persistence;

#nullable disable

namespace WebApolice.Modulos.Documentos.Infrastructure.Migrations
{
    [DbContext(typeof(DocumentosDbContext))]
    partial class DocumentosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApolice.Modulos.Documentos.src.WebApolice.Modulos.Documentos.Infrastructure.Persistence.Models.Arquivo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ArquivoLegado")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("arquivo_legado");

                    b.Property<string>("Bucket")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("bucket");

                    b.Property<string>("CaminhoLegado")
                        .HasColumnType("text")
                        .HasColumnName("caminho_legado");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("CriadoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<int?>("CriadoPorUsuarioLegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_legado_id");

                    b.Property<DateOnly?>("DataDocumento")
                        .HasColumnType("date")
                        .HasColumnName("data_documento");

                    b.Property<DateTime?>("DataUpload")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_upload");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Extensao")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("extensao");

                    b.Property<bool>("ExtensaoConfiavel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("extensao_confiavel");

                    b.Property<string>("ExtensaoNormalizada")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("extensao_normalizada");

                    b.Property<string>("ExtensaoOriginal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("extensao_original");

                    b.Property<string>("HashSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_sha256");

                    b.Property<string>("HoraOriginal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("hora_original");

                    b.Property<int?>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<string>("MigracaoErro")
                        .HasColumnType("text")
                        .HasColumnName("migracao_erro");

                    b.Property<string>("MigracaoStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("migracao_status")
                        .HasDefaultValueSql("'pendente'::character varying");

                    b.Property<string>("MimeType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("mime_type");

                    b.Property<string>("NomeArmazenado")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_armazenado");

                    b.Property<string>("NomeOriginal")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_original");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("origem")
                        .HasDefaultValueSql("'legado'::character varying");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'ativo'::character varying");

                    b.Property<string>("StorageKey")
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<string>("StoragePath")
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<short?>("StorageProviderId")
                        .HasColumnType("smallint")
                        .HasColumnName("storage_provider_id");

                    b.Property<long?>("TamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_bytes");

                    b.Property<string>("Titulo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("titulo");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("arquivo_pkey");

                    b.HasIndex("StorageProviderId");

                    b.HasIndex(new[] { "DataDocumento" }, "ix_arquivo_data_documento");

                    b.HasIndex(new[] { "Extensao" }, "ix_arquivo_extensao");

                    b.HasIndex(new[] { "ExtensaoNormalizada" }, "ix_arquivo_extensao_normalizada");

                    b.HasIndex(new[] { "HashSha256" }, "ix_arquivo_hash");

                    b.HasIndex(new[] { "MigracaoStatus" }, "ix_arquivo_migracao_status");

                    b.HasIndex(new[] { "PublicId" }, "ix_arquivo_public_id");

                    b.HasIndex(new[] { "Status" }, "ix_arquivo_status");

                    b.HasIndex(new[] { "StorageKey" }, "ix_arquivo_storage_key");

                    b.HasIndex(new[] { "LegadoId" }, "ux_arquivo_legado")
                        .IsUnique()
                        .HasFilter("(legado_id IS NOT NULL)");

                    b.ToTable("arquivo", "documento");
                });

            modelBuilder.Entity("WebApolice.Modulos.Documentos.src.WebApolice.Modulos.Documentos.Infrastructure.Persistence.Models.ArquivoAcessoLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("acao");

                    b.Property<long>("ArquivoId")
                        .HasColumnType("bigint")
                        .HasColumnName("arquivo_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IpOrigem")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("ip_origem");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.Property<int?>("UsuarioLegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_legado_id");

                    b.HasKey("Id")
                        .HasName("arquivo_acesso_log_pkey");

                    b.HasIndex(new[] { "ArquivoId" }, "ix_arquivo_acesso_log_arquivo");

                    b.HasIndex(new[] { "CreatedAt" }, "ix_arquivo_acesso_log_data");

                    b.ToTable("arquivo_acesso_log", "documento");
                });

            modelBuilder.Entity("WebApolice.Modulos.Documentos.src.WebApolice.Modulos.Documentos.Infrastructure.Persistence.Models.ArquivoVersao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ArquivoId")
                        .HasColumnType("bigint")
                        .HasColumnName("arquivo_id");

                    b.Property<string>("Bucket")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("bucket");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("CriadoPorUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<int?>("CriadoPorUsuarioLegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_usuario_legado_id");

                    b.Property<string>("Extensao")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("extensao");

                    b.Property<string>("HashSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_sha256");

                    b.Property<string>("MimeType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Motivo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("motivo");

                    b.Property<string>("NomeOriginal")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_original");

                    b.Property<string>("StorageKey")
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<string>("StoragePath")
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<short?>("StorageProviderId")
                        .HasColumnType("smallint")
                        .HasColumnName("storage_provider_id");

                    b.Property<long?>("TamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_bytes");

                    b.Property<int>("Versao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("versao");

                    b.HasKey("Id")
                        .HasName("arquivo_versao_pkey");

                    b.HasIndex("StorageProviderId");

                    b.HasIndex(new[] { "ArquivoId", "Versao" }, "arquivo_versao_arquivo_id_versao_key")
                        .IsUnique();

                    b.HasIndex(new[] { "ArquivoId" }, "ix_arquivo_versao_arquivo");

                    b.ToTable("arquivo_versao", "documento");
                });

            modelBuilder.Entity("WebApolice.Modulos.Documentos.src.WebApolice.Modulos.Documentos.Infrastructure.Persistence.Models.ArquivoVinculo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ArquivoId")
                        .HasColumnType("bigint")
                        .HasColumnName("arquivo_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CriterioResolucao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criterio_resolucao");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("EntidadeId")
                        .HasColumnType("bigint")
                        .HasColumnName("entidade_id");

                    b.Property<string>("EntidadeLegadoChave1")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entidade_legado_chave_1");

                    b.Property<string>("EntidadeLegadoChave2")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entidade_legado_chave_2");

                    b.Property<string>("EntidadeLegadoChaveConcatenada")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("entidade_legado_chave_concatenada");

                    b.Property<int?>("EntidadeLegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("entidade_legado_id");

                    b.Property<string>("EntidadeLegadoTipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entidade_legado_tipo");

                    b.Property<string>("EntidadeTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entidade_tipo");

                    b.Property<string>("LegadoOrigemColuna")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("legado_origem_coluna");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("boolean")
                        .HasColumnName("obrigatorio");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean")
                        .HasColumnName("principal");

                    b.Property<long?>("TipoAnexoId")
                        .HasColumnType("bigint")
                        .HasColumnName("tipo_anexo_id");

                    b.Property<bool>("VinculoResolvido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("vinculo_resolvido");

                    b.HasKey("Id")
                        .HasName("arquivo_vinculo_pkey");

                    b.HasIndex(new[] { "ArquivoId" }, "ix_arquivo_vinculo_arquivo");

                    b.HasIndex(new[] { "EntidadeTipo", "EntidadeId" }, "ix_arquivo_vinculo_entidade");

                    b.HasIndex(new[] { "EntidadeTipo", "EntidadeLegadoId" }, "ix_arquivo_vinculo_legado");

                    b.HasIndex(new[] { "EntidadeLegadoTipo", "EntidadeLegadoChave1", "EntidadeLegadoChave2" }, "ix_arquivo_vinculo_legado_chaves");

                    b.HasIndex(new[] { "TipoAnexoId" }, "ix_arquivo_vinculo_tipo_anexo");

                    b.ToTable("arquivo_vinculo", "documento");
                });

            modelBuilder.Entity("WebApolice.Modulos.Documentos.src.WebApolice.Modulos.Documentos.Infrastructure.Persistence.Models.StorageProvider", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("storage_provider_pkey");

                    b.HasIndex(new[] { "Codigo" }, "storage_provider_codigo_key")
                        .IsUnique();

                    b.ToTable("storage_provider", "documento");
                });

            modelBuilder.Entity("WebApolice.Modulos.Documentos.src.WebApolice.Modulos.Documentos.Infrastructure.Persistence.Models.TipoAnexo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Categoria")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("categoria");

                    b.Property<string>("Codigo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<bool>("ExigeAssinatura")
                        .HasColumnType("boolean")
                        .HasColumnName("exige_assinatura");

                    b.Property<bool>("ExigeValidade")
                        .HasColumnType("boolean")
                        .HasColumnName("exige_validade");

                    b.Property<string>("LegadoValorOriginal")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("legado_valor_original");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<bool>("Sensivel")
                        .HasColumnType("boolean")
                        .HasColumnName("sensivel");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("tipo_anexo_pkey");

                    b.HasIndex(new[] { "Nome" }, "ix_tipo_anexo_nome");

                    b.HasIndex(new[] { "Codigo" }, "ux_tipo_anexo_codigo")
                        .IsUnique()
                        .HasFilter("(codigo IS NOT NULL)");

                    b.ToTable("tipo_anexo", "documento");
                });

            modelBuilder.Entity("WebApolice.Modulos.Documentos.src.WebApolice.Modulos.Documentos.Infrastructure.Persistence.Models.Arquivo", b =>
                {
                    b.HasOne("WebApolice.Modulos.Documentos.src.WebApolice.Modulos.Documentos.Infrastructure.Persistence.Models.StorageProvider", "StorageProvider")
                        .WithMany("Arquivos")
                        .HasForeignKey("StorageProviderId")
                        .HasConstraintName("arquivo_storage_provider_id_fkey");

                    b.Navigation("StorageProvider");
                });

            modelBuilder.Entity("WebApolice.Modulos.Documentos.src.WebApolice.Modulos.Documentos.Infrastructure.Persistence.Models.ArquivoAcessoLog", b =>
                {
                    b.HasOne("WebApolice.Modulos.Documentos.src.WebApolice.Modulos.Documentos.Infrastructure.Persistence.Models.Arquivo", "Arquivo")
                        .WithMany("ArquivoAcessoLogs")
                        .HasForeignKey("ArquivoId")
                        .IsRequired()
                        .HasConstraintName("arquivo_acesso_log_arquivo_id_fkey");

                    b.Navigation("Arquivo");
                });

            modelBuilder.Entity("WebApolice.Modulos.Documentos.src.WebApolice.Modulos.Documentos.Infrastructure.Persistence.Models.ArquivoVersao", b =>
                {
                    b.HasOne("WebApolice.Modulos.Documentos.src.WebApolice.Modulos.Documentos.Infrastructure.Persistence.Models.Arquivo", "Arquivo")
                        .WithMany("ArquivoVersaos")
                        .HasForeignKey("ArquivoId")
                        .IsRequired()
                        .HasConstraintName("arquivo_versao_arquivo_id_fkey");

                    b.HasOne("WebApolice.Modulos.Documentos.src.WebApolice.Modulos.Documentos.Infrastructure.Persistence.Models.StorageProvider", "StorageProvider")
                        .WithMany("ArquivoVersaos")
                        .HasForeignKey("StorageProviderId")
                        .HasConstraintName("arquivo_versao_storage_provider_id_fkey");

                    b.Navigation("Arquivo");

                    b.Navigation("StorageProvider");
                });

            modelBuilder.Entity("WebApolice.Modulos.Documentos.src.WebApolice.Modulos.Documentos.Infrastructure.Persistence.Models.ArquivoVinculo", b =>
                {
                    b.HasOne("WebApolice.Modulos.Documentos.src.WebApolice.Modulos.Documentos.Infrastructure.Persistence.Models.Arquivo", "Arquivo")
                        .WithMany("ArquivoVinculos")
                        .HasForeignKey("ArquivoId")
                        .IsRequired()
                        .HasConstraintName("arquivo_vinculo_arquivo_id_fkey");

                    b.HasOne("WebApolice.Modulos.Documentos.src.WebApolice.Modulos.Documentos.Infrastructure.Persistence.Models.TipoAnexo", "TipoAnexo")
                        .WithMany("ArquivoVinculos")
                        .HasForeignKey("TipoAnexoId")
                        .HasConstraintName("arquivo_vinculo_tipo_anexo_id_fkey");

                    b.Navigation("Arquivo");

                    b.Navigation("TipoAnexo");
                });

            modelBuilder.Entity("WebApolice.Modulos.Documentos.src.WebApolice.Modulos.Documentos.Infrastructure.Persistence.Models.Arquivo", b =>
                {
                    b.Navigation("ArquivoAcessoLogs");

                    b.Navigation("ArquivoVersaos");

                    b.Navigation("ArquivoVinculos");
                });

            modelBuilder.Entity("WebApolice.Modulos.Documentos.src.WebApolice.Modulos.Documentos.Infrastructure.Persistence.Models.StorageProvider", b =>
                {
                    b.Navigation("ArquivoVersaos");

                    b.Navigation("Arquivos");
                });

            modelBuilder.Entity("WebApolice.Modulos.Documentos.src.WebApolice.Modulos.Documentos.Infrastructure.Persistence.Models.TipoAnexo", b =>
                {
                    b.Navigation("ArquivoVinculos");
                });
#pragma warning restore 612, 618
        }
    }
}
