// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence;

#nullable disable

namespace WebApolice.Modulos.Financeiro.Infrastructure.Migrations
{
    [DbContext(typeof(FinanceiroDbContext))]
    [Migration("20261006224700_CriarConveniosCobranca")]
    partial class CriarConveniosCobranca
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.CobrancaAcompanhamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Contato")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("contato");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataAcompanhamento")
                        .HasColumnType("date")
                        .HasColumnName("data_acompanhamento");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("HoraOriginal")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("hora_original");

                    b.Property<int?>("LegadoClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_cliente_id");

                    b.Property<int>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<int?>("UsuarioLegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_legado_id");

                    b.HasKey("Id")
                        .HasName("cobranca_acompanhamento_pkey");

                    b.HasIndex(new[] { "ClienteId" }, "ix_cobranca_acompanhamento_cliente")
                        .HasDatabaseName("ix_cobranca_acompanhamento_cliente_id");

                    b.HasIndex(new[] { "DataAcompanhamento" }, "ix_cobranca_acompanhamento_data")
                        .HasDatabaseName("ix_cobranca_acompanhamento_data_acompanhamento");

                    b.HasIndex(new[] { "LegadoId" }, "ux_cobranca_acompanhamento_legado")
                        .IsUnique()
                        .HasDatabaseName("ix_cobranca_acompanhamento_legado_id");

                    b.ToTable("cobranca_acompanhamento", "financeiro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.ContaCobranca", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<long>("ClienteVinculoId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_vinculo_id");

                    b.Property<long?>("ConvenioCobrancaId")
                        .HasColumnType("bigint")
                        .HasColumnName("convenio_cobranca_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("EstipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("estipulante_id");

                    b.Property<string>("IdentificadorAgrupamento")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("identificador_agrupamento");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<short>("RegraAgrupamentoId")
                        .HasColumnType("smallint")
                        .HasColumnName("regra_agrupamento_id");

                    b.Property<long?>("SubestipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("subestipulante_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("conta_cobranca_pkey");

                    b.HasIndex("ConvenioCobrancaId")
                        .HasDatabaseName("ix_conta_cobranca_convenio_cobranca_id");

                    b.HasIndex("RegraAgrupamentoId")
                        .HasDatabaseName("ix_conta_cobranca_regra_agrupamento_id");

                    b.HasIndex(new[] { "IdentificadorAgrupamento" }, "ix_conta_cobranca_agrupamento")
                        .HasDatabaseName("ix_conta_cobranca_identificador_agrupamento");

                    b.HasIndex(new[] { "PessoaId" }, "ix_conta_cobranca_pessoa")
                        .HasDatabaseName("ix_conta_cobranca_pessoa_id");

                    b.HasIndex(new[] { "ClienteVinculoId" }, "ix_conta_cobranca_vinculo")
                        .HasDatabaseName("ix_conta_cobranca_cliente_vinculo_id");

                    b.ToTable("conta_cobranca", "financeiro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.ConvenioCobranca", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Agencia")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("agencia");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<long?>("BancoId")
                        .HasColumnType("bigint")
                        .HasColumnName("banco_id");

                    b.Property<string>("CodigoEmpresa")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("codigo_empresa");

                    b.Property<bool?>("ComunicaVindi")
                        .HasColumnType("boolean")
                        .HasColumnName("comunica_vindi");

                    b.Property<string>("ContaCorrente")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("conta_corrente");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EstBairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("est_bairro");

                    b.Property<string>("EstCep")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("est_cep");

                    b.Property<string>("EstCidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("est_cidade");

                    b.Property<string>("EstComplemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("est_complemento");

                    b.Property<string>("EstEndereco")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("est_endereco");

                    b.Property<string>("EstNome")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("est_nome");

                    b.Property<string>("EstNumero")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("est_numero");

                    b.Property<string>("EstUf")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("est_uf");

                    b.Property<string>("ExtensaoArquivo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("extensao_arquivo");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("inscricao_estadual");

                    b.Property<short?>("LayoutArquivo")
                        .HasColumnType("smallint")
                        .HasColumnName("layout_arquivo");

                    b.Property<int?>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<string>("LocalRemessaArquivo")
                        .HasColumnType("text")
                        .HasColumnName("local_remessa_arquivo");

                    b.Property<string>("LocalRetornoArquivo")
                        .HasColumnType("text")
                        .HasColumnName("local_retorno_arquivo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeEmpresa")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_empresa");

                    b.Property<string>("NomeInicialArquivo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome_inicial_arquivo");

                    b.Property<int?>("NumeroArquivo")
                        .HasColumnType("integer")
                        .HasColumnName("numero_arquivo");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("convenio_cobranca_pkey");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_convenio_cobranca_public_id");

                    b.HasIndex(new[] { "BancoId" }, "ix_convenio_cobranca_banco")
                        .HasDatabaseName("ix_convenio_cobranca_banco_id");

                    b.HasIndex(new[] { "LegadoId" }, "ux_convenio_cobranca_legado")
                        .IsUnique()
                        .HasDatabaseName("ix_convenio_cobranca_legado_id")
                        .HasFilter("(legado_id IS NOT NULL)");

                    b.ToTable("convenio_cobranca", "financeiro");
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.EstipulanteFaturamentoConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Campanha")
                        .HasColumnType("integer")
                        .HasColumnName("campanha");

                    b.Property<long?>("ConvenioCobrancaId")
                        .HasColumnType("bigint")
                        .HasColumnName("convenio_cobranca_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DiaDebito")
                        .HasColumnType("integer")
                        .HasColumnName("dia_debito");

                    b.Property<long>("EstipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("estipulante_id");

                    b.Property<long?>("FormaPagamentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("forma_pagamento_id");

                    b.Property<decimal?>("IofAp")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("iof_ap");

                    b.Property<decimal?>("IofInc")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("iof_inc");

                    b.Property<decimal?>("IofVg")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("iof_vg");

                    b.Property<string>("NumeroPropostaAp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_proposta_ap");

                    b.Property<string>("NumeroPropostaInc")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_proposta_inc");

                    b.Property<string>("NumeroPropostaVg")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_proposta_vg");

                    b.Property<long?>("ParametroSiapeId")
                        .HasColumnType("bigint")
                        .HasColumnName("parametro_siape_id");

                    b.Property<short?>("RegraAgrupamentoFaturaId")
                        .HasColumnType("smallint")
                        .HasColumnName("regra_agrupamento_fatura_id");

                    b.Property<string>("Saf")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("saf");

                    b.Property<decimal?>("SorteioValor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sorteio_valor");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("estipulante_faturamento_config_pkey");

                    b.HasIndex("RegraAgrupamentoFaturaId")
                        .HasDatabaseName("ix_estipulante_faturamento_config_regra_agrupamento_fatura_id");

                    b.HasIndex(new[] { "ConvenioCobrancaId" }, "ix_estipulante_faturamento_convenio")
                        .HasDatabaseName("ix_estipulante_faturamento_config_convenio_cobranca_id");

                    b.HasIndex(new[] { "FormaPagamentoId" }, "ix_estipulante_faturamento_forma")
                        .HasDatabaseName("ix_estipulante_faturamento_config_forma_pagamento_id");

                    b.HasIndex(new[] { "EstipulanteId" }, "ux_estipulante_faturamento_config")
                        .IsUnique()
                        .HasDatabaseName("ix_estipulante_faturamento_config_estipulante_id");

                    b.ToTable("estipulante_faturamento_config", "financeiro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.FormaPagamentoEstipulante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("forma_pagamento_estipulante_pkey");

                    b.HasIndex(new[] { "LegadoId" }, "ux_forma_pagamento_estipulante_legado")
                        .IsUnique()
                        .HasDatabaseName("ix_forma_pagamento_estipulante_legado_id")
                        .HasFilter("(legado_id IS NOT NULL)");

                    b.ToTable("forma_pagamento_estipulante", "financeiro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.FormaRetorno", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("forma_retorno_pkey");

                    b.HasIndex(new[] { "LegadoId" }, "ux_forma_retorno_legado")
                        .IsUnique()
                        .HasDatabaseName("ix_forma_retorno_legado_id");

                    b.ToTable("forma_retorno", "financeiro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.FormaRetornoEstipulante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("EstipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("estipulante_id");

                    b.Property<long>("FormaRetornoId")
                        .HasColumnType("bigint")
                        .HasColumnName("forma_retorno_id");

                    b.Property<int?>("LegadoEstipulanteId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_estipulante_id");

                    b.Property<int?>("LegadoFormaRetornoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_forma_retorno_id");

                    b.Property<int>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.HasKey("Id")
                        .HasName("forma_retorno_estipulante_pkey");

                    b.HasIndex(new[] { "EstipulanteId" }, "ix_forma_retorno_estipulante_estipulante")
                        .HasDatabaseName("ix_forma_retorno_estipulante_estipulante_id");

                    b.HasIndex(new[] { "FormaRetornoId" }, "ix_forma_retorno_estipulante_forma")
                        .HasDatabaseName("ix_forma_retorno_estipulante_forma_retorno_id");

                    b.HasIndex(new[] { "LegadoId" }, "ux_forma_retorno_estipulante_legado")
                        .IsUnique()
                        .HasDatabaseName("ix_forma_retorno_estipulante_legado_id");

                    b.ToTable("forma_retorno_estipulante", "financeiro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.IdentificadorRemessaApi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("Datahora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datahora");

                    b.Property<int>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<int?>("UsuarioLegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_legado_id");

                    b.HasKey("Id")
                        .HasName("identificador_remessa_api_pkey");

                    b.HasIndex(new[] { "Datahora" }, "ix_identificador_remessa_api_datahora")
                        .HasDatabaseName("ix_identificador_remessa_api_datahora");

                    b.HasIndex(new[] { "LegadoId" }, "ux_identificador_remessa_api_legado")
                        .IsUnique()
                        .HasDatabaseName("ix_identificador_remessa_api_legado_id");

                    b.ToTable("identificador_remessa_api", "financeiro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.MovimentoCobrancaLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime?>("DataMovimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_movimento");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date")
                        .HasColumnName("data_pagamento");

                    b.Property<int>("LegadoMovimentoPropostaId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_movimento_proposta_id");

                    b.Property<long?>("PropostaMovimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_movimento_id");

                    b.Property<long?>("TituloId")
                        .HasColumnType("bigint")
                        .HasColumnName("titulo_id");

                    b.Property<int?>("UsuarioLegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_legado_id");

                    b.Property<decimal?>("ValorPagamento")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_pagamento");

                    b.HasKey("Id")
                        .HasName("movimento_cobranca_log_pkey");

                    b.HasIndex(new[] { "DataMovimento" }, "ix_movimento_cobranca_log_data")
                        .HasDatabaseName("ix_movimento_cobranca_log_data_movimento");

                    b.HasIndex(new[] { "LegadoMovimentoPropostaId" }, "ix_movimento_cobranca_log_legado_movimento")
                        .HasDatabaseName("ix_movimento_cobranca_log_legado_movimento_proposta_id");

                    b.HasIndex(new[] { "PropostaMovimentoId" }, "ix_movimento_cobranca_log_movimento")
                        .HasDatabaseName("ix_movimento_cobranca_log_proposta_movimento_id");

                    b.HasIndex(new[] { "TituloId" }, "ix_movimento_cobranca_log_titulo")
                        .HasDatabaseName("ix_movimento_cobranca_log_titulo_id");

                    b.ToTable("movimento_cobranca_log", "financeiro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.RegraAgrupamentoFatura", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("regra_agrupamento_fatura_pkey");

                    b.HasIndex(new[] { "Codigo" }, "regra_agrupamento_fatura_codigo_key")
                        .IsUnique()
                        .HasDatabaseName("ix_regra_agrupamento_fatura_codigo");

                    b.ToTable("regra_agrupamento_fatura", "financeiro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.RetornoBancarioCodigo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<bool>("GeraBaixa")
                        .HasColumnType("boolean")
                        .HasColumnName("gera_baixa");

                    b.Property<bool>("GeraRejeicao")
                        .HasColumnType("boolean")
                        .HasColumnName("gera_rejeicao");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo")
                        .HasDefaultValueSql("'indefinido'::character varying");

                    b.HasKey("Id")
                        .HasName("retorno_bancario_codigo_pkey");

                    b.HasIndex(new[] { "Codigo" }, "ix_retorno_bancario_codigo_codigo")
                        .HasDatabaseName("ix_retorno_bancario_codigo_codigo");

                    b.HasIndex(new[] { "Tipo" }, "ix_retorno_bancario_codigo_tipo")
                        .HasDatabaseName("ix_retorno_bancario_codigo_tipo");

                    b.HasIndex(new[] { "Codigo", "Descricao" }, "retorno_bancario_codigo_codigo_descricao_key")
                        .IsUnique()
                        .HasDatabaseName("ix_retorno_bancario_codigo_codigo_descricao");

                    b.ToTable("retorno_bancario_codigo", "financeiro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.Titulo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<long?>("ClienteVinculoId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_vinculo_id");

                    b.Property<bool?>("CobrarNaFatura")
                        .HasColumnType("boolean")
                        .HasColumnName("cobrar_na_fatura");

                    b.Property<int?>("CompetenciaAno")
                        .HasColumnType("integer")
                        .HasColumnName("competencia_ano");

                    b.Property<int?>("CompetenciaInt")
                        .HasColumnType("integer")
                        .HasColumnName("competencia_int");

                    b.Property<int?>("CompetenciaMes")
                        .HasColumnType("integer")
                        .HasColumnName("competencia_mes");

                    b.Property<long?>("ContaCobrancaId")
                        .HasColumnType("bigint")
                        .HasColumnName("conta_cobranca_id");

                    b.Property<long?>("ConvenioCobrancaId")
                        .HasColumnType("bigint")
                        .HasColumnName("convenio_cobranca_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataLancamento")
                        .HasColumnType("date")
                        .HasColumnName("data_lancamento");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date")
                        .HasColumnName("data_pagamento");

                    b.Property<DateOnly?>("DataRecebimentoFatura")
                        .HasColumnType("date")
                        .HasColumnName("data_recebimento_fatura");

                    b.Property<DateOnly?>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<DateOnly?>("DataVencimentoFatura")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento_fatura");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("EstipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("estipulante_id");

                    b.Property<string>("IdFaturaCartao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id_fatura_cartao");

                    b.Property<decimal?>("Iof")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("iof");

                    b.Property<int?>("LegadoMovimentoPropostaId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_movimento_proposta_id");

                    b.Property<int?>("LegadoPropostaId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_proposta_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<int?>("Parcela")
                        .HasColumnType("integer")
                        .HasColumnName("parcela");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<decimal?>("PremioAnterior")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("premio_anterior");

                    b.Property<decimal?>("PremioAtual")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("premio_atual");

                    b.Property<decimal?>("PremioDiferenca")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("premio_diferenca");

                    b.Property<decimal?>("PremioFatura")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("premio_fatura");

                    b.Property<decimal?>("PremioLiquido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("premio_liquido");

                    b.Property<decimal?>("PremioTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("premio_total");

                    b.Property<decimal?>("PremioTotalOriginal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("premio_total_original");

                    b.Property<long?>("PropostaId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_id");

                    b.Property<long?>("PropostaMovimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_movimento_id");

                    b.Property<int?>("Sequencia")
                        .HasColumnType("integer")
                        .HasColumnName("sequencia");

                    b.Property<short>("StatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("status_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("ValorAtual")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_atual");

                    b.Property<decimal?>("ValorOriginal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_original");

                    b.Property<decimal?>("ValorPago")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_pago");

                    b.HasKey("Id")
                        .HasName("titulo_pkey");

                    b.HasIndex("ContaCobrancaId")
                        .HasDatabaseName("ix_titulo_conta_cobranca_id");

                    b.HasIndex("ConvenioCobrancaId")
                        .HasDatabaseName("ix_titulo_convenio_cobranca_id");

                    b.HasIndex(new[] { "ClienteId" }, "ix_titulo_cliente")
                        .HasDatabaseName("ix_titulo_cliente_id");

                    b.HasIndex(new[] { "CompetenciaAno", "CompetenciaMes" }, "ix_titulo_competencia")
                        .HasDatabaseName("ix_titulo_competencia_ano_competencia_mes");

                    b.HasIndex(new[] { "CompetenciaInt" }, "ix_titulo_competencia_int")
                        .HasDatabaseName("ix_titulo_competencia_int");

                    b.HasIndex(new[] { "EstipulanteId" }, "ix_titulo_estipulante")
                        .HasDatabaseName("ix_titulo_estipulante_id");

                    b.HasIndex(new[] { "DataPagamento" }, "ix_titulo_pagamento")
                        .HasDatabaseName("ix_titulo_data_pagamento")
                        .HasFilter("(data_pagamento IS NOT NULL)");

                    b.HasIndex(new[] { "PropostaId" }, "ix_titulo_proposta")
                        .HasDatabaseName("ix_titulo_proposta_id");

                    b.HasIndex(new[] { "StatusId" }, "ix_titulo_status")
                        .HasDatabaseName("ix_titulo_status_id");

                    b.HasIndex(new[] { "ClienteVinculoId" }, "ix_titulo_vinculo")
                        .HasDatabaseName("ix_titulo_cliente_vinculo_id");

                    b.HasIndex(new[] { "LegadoMovimentoPropostaId" }, "ux_titulo_legado_movimento")
                        .IsUnique()
                        .HasDatabaseName("ix_titulo_legado_movimento_proposta_id")
                        .HasFilter("(legado_movimento_proposta_id IS NOT NULL)");

                    b.ToTable("titulo", "financeiro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.TituloPagamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date")
                        .HasColumnName("data_pagamento");

                    b.Property<string>("FormaPagamento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("forma_pagamento");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("origem")
                        .HasDefaultValueSql("'legado'::character varying");

                    b.Property<long?>("PropostaMovimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_movimento_id");

                    b.Property<long>("TituloId")
                        .HasColumnType("bigint")
                        .HasColumnName("titulo_id");

                    b.Property<decimal>("ValorPago")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_pago");

                    b.HasKey("Id")
                        .HasName("titulo_pagamento_pkey");

                    b.HasIndex(new[] { "DataPagamento" }, "ix_titulo_pagamento_data")
                        .HasDatabaseName("ix_titulo_pagamento_data_pagamento");

                    b.HasIndex(new[] { "TituloId" }, "ix_titulo_pagamento_titulo")
                        .HasDatabaseName("ix_titulo_pagamento_titulo_id");

                    b.ToTable("titulo_pagamento", "financeiro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.TituloRetornoBancario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoOriginal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_original");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataRetorno")
                        .HasColumnType("date")
                        .HasColumnName("data_retorno");

                    b.Property<string>("DescricaoOriginal")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao_original");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<long?>("PropostaMovimentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_movimento_id");

                    b.Property<long?>("RetornoCodigoId")
                        .HasColumnType("bigint")
                        .HasColumnName("retorno_codigo_id");

                    b.Property<long?>("TituloId")
                        .HasColumnType("bigint")
                        .HasColumnName("titulo_id");

                    b.HasKey("Id")
                        .HasName("titulo_retorno_bancario_pkey");

                    b.HasIndex(new[] { "RetornoCodigoId" }, "ix_titulo_retorno_codigo")
                        .HasDatabaseName("ix_titulo_retorno_bancario_retorno_codigo_id");

                    b.HasIndex(new[] { "PropostaMovimentoId" }, "ix_titulo_retorno_movimento")
                        .HasDatabaseName("ix_titulo_retorno_bancario_proposta_movimento_id");

                    b.HasIndex(new[] { "TituloId" }, "ix_titulo_retorno_titulo")
                        .HasDatabaseName("ix_titulo_retorno_bancario_titulo_id");

                    b.ToTable("titulo_retorno_bancario", "financeiro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.TituloStatus", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<bool>("Finalizador")
                        .HasColumnType("boolean")
                        .HasColumnName("finalizador");

                    b.Property<bool>("Inadimplente")
                        .HasColumnType("boolean")
                        .HasColumnName("inadimplente");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<bool>("PermiteCobranca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("permite_cobranca");

                    b.HasKey("Id")
                        .HasName("titulo_status_pkey");

                    b.HasIndex(new[] { "Codigo" }, "titulo_status_codigo_key")
                        .IsUnique()
                        .HasDatabaseName("ix_titulo_status_codigo");

                    b.ToTable("titulo_status", "financeiro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.ContaCobranca", b =>
                {
                    b.HasOne("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.ConvenioCobranca", "ConvenioCobranca")
                        .WithMany("ContaCobrancas")
                        .HasForeignKey("ConvenioCobrancaId")
                        .HasConstraintName("conta_cobranca_convenio_cobranca_id_fkey");

                    b.HasOne("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.RegraAgrupamentoFatura", "RegraAgrupamento")
                        .WithMany("ContaCobrancas")
                        .HasForeignKey("RegraAgrupamentoId")
                        .IsRequired()
                        .HasConstraintName("conta_cobranca_regra_agrupamento_id_fkey");

                    b.Navigation("ConvenioCobranca");

                    b.Navigation("RegraAgrupamento");
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.EstipulanteFaturamentoConfig", b =>
                {
                    b.HasOne("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.ConvenioCobranca", "ConvenioCobranca")
                        .WithMany("EstipulanteFaturamentoConfigs")
                        .HasForeignKey("ConvenioCobrancaId")
                        .HasConstraintName("estipulante_faturamento_config_convenio_cobranca_id_fkey");

                    b.HasOne("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.FormaPagamentoEstipulante", "FormaPagamento")
                        .WithMany("EstipulanteFaturamentoConfigs")
                        .HasForeignKey("FormaPagamentoId")
                        .HasConstraintName("estipulante_faturamento_config_forma_pagamento_id_fkey");

                    b.HasOne("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.RegraAgrupamentoFatura", "RegraAgrupamentoFatura")
                        .WithMany("EstipulanteFaturamentoConfigs")
                        .HasForeignKey("RegraAgrupamentoFaturaId")
                        .HasConstraintName("estipulante_faturamento_config_regra_agrupamento_fatura_id_fkey");

                    b.Navigation("ConvenioCobranca");

                    b.Navigation("FormaPagamento");

                    b.Navigation("RegraAgrupamentoFatura");
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.FormaRetornoEstipulante", b =>
                {
                    b.HasOne("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.FormaRetorno", "FormaRetorno")
                        .WithMany("FormaRetornoEstipulantes")
                        .HasForeignKey("FormaRetornoId")
                        .IsRequired()
                        .HasConstraintName("forma_retorno_estipulante_forma_retorno_id_fkey");

                    b.Navigation("FormaRetorno");
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.MovimentoCobrancaLog", b =>
                {
                    b.HasOne("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.Titulo", "Titulo")
                        .WithMany("MovimentoCobrancaLogs")
                        .HasForeignKey("TituloId")
                        .HasConstraintName("movimento_cobranca_log_titulo_id_fkey");

                    b.Navigation("Titulo");
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.Titulo", b =>
                {
                    b.HasOne("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.ContaCobranca", "ContaCobranca")
                        .WithMany("Titulos")
                        .HasForeignKey("ContaCobrancaId")
                        .HasConstraintName("titulo_conta_cobranca_id_fkey");

                    b.HasOne("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.ConvenioCobranca", "ConvenioCobranca")
                        .WithMany("Titulos")
                        .HasForeignKey("ConvenioCobrancaId")
                        .HasConstraintName("titulo_convenio_cobranca_id_fkey");

                    b.HasOne("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.TituloStatus", "Status")
                        .WithMany("Titulos")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("titulo_status_id_fkey");

                    b.Navigation("ContaCobranca");

                    b.Navigation("ConvenioCobranca");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.TituloPagamento", b =>
                {
                    b.HasOne("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.Titulo", "Titulo")
                        .WithMany("TituloPagamentos")
                        .HasForeignKey("TituloId")
                        .IsRequired()
                        .HasConstraintName("titulo_pagamento_titulo_id_fkey");

                    b.Navigation("Titulo");
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.TituloRetornoBancario", b =>
                {
                    b.HasOne("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.RetornoBancarioCodigo", "RetornoCodigo")
                        .WithMany("TituloRetornoBancarios")
                        .HasForeignKey("RetornoCodigoId")
                        .HasConstraintName("titulo_retorno_bancario_retorno_codigo_id_fkey");

                    b.HasOne("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.Titulo", "Titulo")
                        .WithMany("TituloRetornoBancarios")
                        .HasForeignKey("TituloId")
                        .HasConstraintName("titulo_retorno_bancario_titulo_id_fkey");

                    b.Navigation("RetornoCodigo");

                    b.Navigation("Titulo");
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.ContaCobranca", b =>
                {
                    b.Navigation("Titulos");
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.ConvenioCobranca", b =>
                {
                    b.Navigation("ContaCobrancas");

                    b.Navigation("EstipulanteFaturamentoConfigs");

                    b.Navigation("Titulos");
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.FormaPagamentoEstipulante", b =>
                {
                    b.Navigation("EstipulanteFaturamentoConfigs");
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.FormaRetorno", b =>
                {
                    b.Navigation("FormaRetornoEstipulantes");
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.RegraAgrupamentoFatura", b =>
                {
                    b.Navigation("ContaCobrancas");

                    b.Navigation("EstipulanteFaturamentoConfigs");
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.RetornoBancarioCodigo", b =>
                {
                    b.Navigation("TituloRetornoBancarios");
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.Titulo", b =>
                {
                    b.Navigation("MovimentoCobrancaLogs");

                    b.Navigation("TituloPagamentos");

                    b.Navigation("TituloRetornoBancarios");
                });

            modelBuilder.Entity("WebApolice.Modulos.Financeiro.src.WebApolice.Modulos.Financeiro.Infrastructure.Persistence.Models.TituloStatus", b =>
                {
                    b.Navigation("Titulos");
                });
#pragma warning restore 612, 618
        }
    }
}
