using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace WebApolice.Modulos.Cadastro.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class CriarTabelaClienteDependente : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS cadastro.cliente_dependente (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    cliente_id bigint NOT NULL,
                    pessoa_id bigint,
                    tipo_relacao text NOT NULL,
                    nome text NOT NULL,
                    cpf text,
                    data_nascimento date,
                    created_at timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT fk_cliente_dependente_cliente_cliente_id
                        FOREIGN KEY (cliente_id) REFERENCES cadastro.cliente(id) ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS ix_cliente_dependente_cliente_id
                    ON cadastro.cliente_dependente (cliente_id);
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS cadastro.cliente_dependente;");
        }
    }
}

