// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApolice.Modulos.Cadastro.Infrastructure.Persistence;

#nullable disable

namespace WebApolice.Modulos.Cadastro.Infrastructure.Migrations
{
    [DbContext(typeof(CadastroDbContext))]
    [Migration("20260818031145_AdicionarCadastroModulosGlobais")]
    partial class AdicionarCadastroModulosGlobais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Domain.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DataCadastroLegado")
                        .HasColumnType("date")
                        .HasColumnName("data_cadastro_legado");

                    b.Property<DateOnly?>("DataObito")
                        .HasColumnType("date")
                        .HasColumnName("data_obito");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("Falecido")
                        .HasColumnType("boolean")
                        .HasColumnName("falecido");

                    b.Property<int?>("LegadoId")
                        .HasColumnType("integer")
                        .HasColumnName("legado_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("Re")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("re");

                    b.Property<short>("StatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("status_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cliente");

                    b.ToTable("cliente", "cadastro");
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.ClienteDependenteModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Cpf")
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<string>("TipoRelacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_relacao");

                    b.HasKey("Id")
                        .HasName("pk_cliente_dependente");

                    b.ToTable("cliente_dependente", "cadastro");
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.ClienteStatusModel", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_cliente_status");

                    b.ToTable("cliente_status", "cadastro");
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.ClienteVinculoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Agencia")
                        .HasColumnType("text")
                        .HasColumnName("agencia");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<long?>("BancoId")
                        .HasColumnType("bigint")
                        .HasColumnName("banco_id");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<string>("ContaCorrente")
                        .HasColumnType("text")
                        .HasColumnName("conta_corrente");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("EstipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("estipulante_id");

                    b.Property<long?>("GrupoId")
                        .HasColumnType("bigint")
                        .HasColumnName("grupo_id");

                    b.Property<long?>("LotacaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("lotacao_id");

                    b.Property<string>("Matricula")
                        .HasColumnType("text")
                        .HasColumnName("matricula");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<long?>("SubestipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("subestipulante_id");

                    b.Property<long?>("SubgrupoId")
                        .HasColumnType("bigint")
                        .HasColumnName("subgrupo_id");

                    b.HasKey("Id")
                        .HasName("pk_cliente_vinculo");

                    b.ToTable("cliente_vinculo", "cadastro");
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.EstipulanteConfiguracaoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Adesao")
                        .HasColumnType("text")
                        .HasColumnName("adesao");

                    b.Property<string>("AdesaoPor")
                        .HasColumnType("text")
                        .HasColumnName("adesao_por");

                    b.Property<long?>("CancelaEstipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cancela_estipulante_id");

                    b.Property<int?>("Carencia")
                        .HasColumnType("integer")
                        .HasColumnName("carencia");

                    b.Property<bool?>("ControlaComissao")
                        .HasColumnType("boolean")
                        .HasColumnName("controla_comissao");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Custeio")
                        .HasColumnType("text")
                        .HasColumnName("custeio");

                    b.Property<DateOnly?>("DataAniversario")
                        .HasColumnType("date")
                        .HasColumnName("data_aniversario");

                    b.Property<int?>("DataBaseReajuste")
                        .HasColumnType("integer")
                        .HasColumnName("data_base_reajuste");

                    b.Property<DateOnly?>("DataFimVigencia")
                        .HasColumnType("date")
                        .HasColumnName("data_fim_vigencia");

                    b.Property<DateOnly?>("DataInicioVigencia")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio_vigencia");

                    b.Property<DateOnly?>("DataLimiteReajuste")
                        .HasColumnType("date")
                        .HasColumnName("data_limite_reajuste");

                    b.Property<DateOnly?>("DataUltimoReajuste")
                        .HasColumnType("date")
                        .HasColumnName("data_ultimo_reajuste");

                    b.Property<bool>("DesconsiderarPropostaAtiva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("desconsiderar_proposta_ativa");

                    b.Property<int?>("DiasAvisoReajuste")
                        .HasColumnType("integer")
                        .HasColumnName("dias_aviso_reajuste");

                    b.Property<long>("EstipulanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("estipulante_id");

                    b.Property<int?>("FaixaEtariaFim")
                        .HasColumnType("integer")
                        .HasColumnName("faixa_etaria_fim");

                    b.Property<int?>("FaixaEtariaInicio")
                        .HasColumnType("integer")
                        .HasColumnName("faixa_etaria_inicio");

                    b.Property<bool?>("PermitePropostas")
                        .HasColumnType("boolean")
                        .HasColumnName("permite_propostas");

                    b.Property<bool>("PermitirProtocoloDuplicado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("permitir_protocolo_duplicado");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_estipulante_configuracao");

                    b.HasIndex("EstipulanteId")
                        .IsUnique()
                        .HasDatabaseName("ix_estipulante_configuracao_estipulante_id");

                    b.ToTable("estipulante_configuracao", "cadastro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.EstipulanteModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<long?>("CidadeId")
                        .HasColumnType("bigint")
                        .HasColumnName("cidade_id");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text")
                        .HasColumnName("cnpj");

                    b.Property<string>("CnpjLimpo")
                        .HasColumnType("text")
                        .HasColumnName("cnpj_limpo");

                    b.Property<string>("Codigo")
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("GrupoId")
                        .HasColumnType("bigint")
                        .HasColumnName("grupo_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("NomeFormatado")
                        .HasColumnType("text")
                        .HasColumnName("nome_formatado");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<long?>("SeguradoraId")
                        .HasColumnType("bigint")
                        .HasColumnName("seguradora_id");

                    b.Property<short?>("TipoPessoa")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_pessoa");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_estipulante");

                    b.HasIndex("PessoaId")
                        .HasDatabaseName("ix_estipulante_pessoa_id");

                    b.ToTable("estipulante", "cadastro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.ModuloModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_modulo");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_modulo_ativo")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_modulo_nome");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_modulo_public_id");

                    b.ToTable("modulo", "cadastro");
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.PessoaContatoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean")
                        .HasColumnName("principal");

                    b.Property<string>("TipoContato")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_contato");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.Property<string>("ValorNormalizado")
                        .HasColumnType("text")
                        .HasColumnName("valor_normalizado");

                    b.HasKey("Id")
                        .HasName("pk_pessoa_contato");

                    b.ToTable("pessoa_contato", "core", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.PessoaEnderecoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Bairro")
                        .HasColumnType("text")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<long?>("CidadeId")
                        .HasColumnType("bigint")
                        .HasColumnName("cidade_id");

                    b.Property<string>("Complemento")
                        .HasColumnType("text")
                        .HasColumnName("complemento");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("LegadoSituacaoEndereco")
                        .HasColumnType("integer")
                        .HasColumnName("legado_situacao_endereco");

                    b.Property<string>("Logradouro")
                        .HasColumnType("text")
                        .HasColumnName("logradouro");

                    b.Property<string>("Numero")
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean")
                        .HasColumnName("principal");

                    b.Property<string>("TipoEndereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_endereco");

                    b.Property<string>("Uf")
                        .HasColumnType("text")
                        .HasColumnName("uf");

                    b.HasKey("Id")
                        .HasName("pk_pessoa_endereco");

                    b.ToTable("pessoa_endereco", "core", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.PessoaModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_nascimento");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DocumentoPrincipal")
                        .HasColumnType("text")
                        .HasColumnName("documento_principal");

                    b.Property<string>("DocumentoPrincipalLimpo")
                        .HasColumnType("text")
                        .HasColumnName("documento_principal_limpo");

                    b.Property<bool>("DocumentoValido")
                        .HasColumnType("boolean")
                        .HasColumnName("documento_valido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("NomeNormalizado")
                        .HasColumnType("text")
                        .HasColumnName("nome_normalizado");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<short?>("Sexo")
                        .HasColumnType("smallint")
                        .HasColumnName("sexo");

                    b.Property<short>("TipoPessoa")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_pessoa");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pessoa");

                    b.ToTable("pessoa", "core", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.Vinculos.AgenciadorModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.HasKey("Id")
                        .HasName("pk_agenciador");

                    b.ToTable("agenciador", "cadastro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.Vinculos.BancoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_banco");

                    b.ToTable("banco", "core", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.Vinculos.CidadeModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_cidade");

                    b.ToTable("cidade", "core", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.Vinculos.CorretoraModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.HasKey("Id")
                        .HasName("pk_corretora");

                    b.ToTable("corretora", "cadastro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.Vinculos.GrupoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_grupo");

                    b.ToTable("grupo", "cadastro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.Vinculos.LotacaoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_lotacao");

                    b.ToTable("lotacao", "cadastro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.Vinculos.PessoaContatoInstitucionalModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("departamento");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<string>("Ramal")
                        .HasColumnType("text")
                        .HasColumnName("ramal");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_pessoa_contato_institucional");

                    b.ToTable("pessoa_contato_institucional", "core", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.Vinculos.SeguradoraModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.HasKey("Id")
                        .HasName("pk_seguradora");

                    b.ToTable("seguradora", "cadastro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.Vinculos.SubestipulanteModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pessoa_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.HasKey("Id")
                        .HasName("pk_subestipulante");

                    b.ToTable("subestipulante", "cadastro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.Vinculos.SubgrupoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_subgrupo");

                    b.ToTable("subgrupo", "cadastro", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.EstipulanteConfiguracaoModel", b =>
                {
                    b.HasOne("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.EstipulanteModel", "Estipulante")
                        .WithOne("Configuracao")
                        .HasForeignKey("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.EstipulanteConfiguracaoModel", "EstipulanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estipulante_configuracao_estipulantes_estipulante_id");

                    b.Navigation("Estipulante");
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.EstipulanteModel", b =>
                {
                    b.HasOne("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.PessoaModel", "Pessoa")
                        .WithMany("Estipulantes")
                        .HasForeignKey("PessoaId")
                        .HasConstraintName("fk_estipulante_pessoas_pessoa_id");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.EstipulanteModel", b =>
                {
                    b.Navigation("Configuracao");
                });

            modelBuilder.Entity("WebApolice.Modulos.Cadastro.Infrastructure.Persistence.Models.PessoaModel", b =>
                {
                    b.Navigation("Estipulantes");
                });
#pragma warning restore 612, 618
        }
    }
}
